### ISSUE TITLE
spectband dimension and associated bounds

### ISSUE THREAD

**Issue by martinjuckes** [PCMDI/cmor#101]
There is a new dimension in the request: "spectband", which defines spectral bands used for some radiation diagnostics. It should be provided with a bounds array, but the values of the axis and the bounds are to be specified by the modelling group. Should there be a suitable "_bnds" array defined, e.g. "spect_bnds"? I'm not sure what the process is here .. if you need more information from me please let me know.

**Comment by dnadeau4** [comment]
@taylor13 Can you answer this?

**Comment by taylor13** [comment]
@martinjuckes   You already have included "spectband" as one of your coordinates (axes?), and you indicated must_have_bounds="yes", so that's all you have to do.  CMOR constructs the name of the bounds variable, in this case "spectband_bounds".  So I don't think any further action is needed on your part.  [If required or requested bands were needed, they would have had to be listed in your data request, but you indicate it's up to the user how to split the spectrum.

**Comment by wachsylon** [comment]
@taylor13 How do I configure CMOR if `spectband` includes only one band? Then there should be a singleton coordinate like `height2m`, correct? But since CMOR has no information about the value, the user can not just avoid cmor_axis. If I do register `spectband` with one value, I receive:

```
 ncdump -h .//CMIP6/CMIP/MPI-M/MPI-ESM1-2-HR/historical/r1i1p1f1/E3hrPt/aeroptbnd/gn/v20190627/aeroptbnd_E3hrPt_MPI-ESM1-2-HR_historical_r1i1p1f1_gn_201501010256-201501010856.nc
netcdf aeroptbnd_E3hrPt_MPI-ESM1-2-HR_historical_r1i1p1f1_gn_201501010256-201501010856 {
dimensions:
	time = UNLIMITED ; // (3 currently)
	spectband = 1 ;
	lev = 95 ;
	lat = 192 ;
	lon = 384 ;
	bnds = 2 ;
variables:
	double time(time) ;
		time:units = "days since 1850-1-1 00:00:00" ;
		time:calendar = "proleptic_gregorian" ;
		time:axis = "T" ;
		time:long_name = "time" ;
		time:standard_name = "time" ;
	double spectband(spectband) ;
		spectband:bounds = "spectband_bnds" ;
		spectband:units = "m-1" ;
		spectband:long_name = "Spectral Frequency Band" ;
		spectband:standard_name = "sensor_band_central_radiation_wavenumber" ;
	double spectband_bnds(spectband, bnds) ;
```

**Comment by taylor13** [comment]
I think this file is correctly written.  It is true that I usually prefer to record scalar dimensions by pointing to them with the "coordinates" attribute, but it is perfectly acceptable (according to the CF conventions) to record them as explicit dimensions of length 1, as in your sample file above.  

Since in CMIP6, many models will have multiple bands, rather than a single spectral band, I think it is better to explicitly include spectband as a dimension for *all* models so that aeroptbnd is an explicit function of (longitude latitude alevel spectband time1), even though spectband might be only length 1.

Do you agree?

**Comment by wachsylon** [comment]
I agree. I will consult my colleagues tomorrow if they have some thoughts about this.

If we allow this for `spectband` - which coordinates can be recorded in that way? All coordinates that have no value requested in coordinate.json? I think there are other suspects like `soilpools` and `iceband` but maybe we can think bigger and include all generic levels.

Just a side note: In MPI-ESM1-2-HR `spectband` varies within the model output meaning that `aeroptbnd` will have other `spectbands` than `albdiffbnd`. So it seems to be well defined in the DReq without any values (but it is hard to configure this with `cdo cmor`).

**Comment by taylor13** [comment]
If in a CMOR table `value=""`, then CMOR will include the coordinate as an explicit dimension.  If `value` is not an empty string, CMOR will define a "coordinates" attribute and include the scalar dimension there.  The user can override the default value specified by `value` by calling `cmor_axis` for the coordinate and pass a value to override the default as in the example: https://github.com/PCMDI/cmor/blob/master/Test/test_singleton.f90 .

**Comment by mauzey1** [comment]
@taylor13 @wachsylon Should this issue be closed again?

**Comment by taylor13** [comment]
Yes, I think we can close it.  If @wachsylon objects, we'll reopen.
