### ISSUE TITLE
cell_measures with a value of --MODEL

### ISSUE THREAD

**Issue by ehogan** [PCMDI/cmor#120]
Sort of related to #108 (see also the links on  cmip6dr/CMIP6_DataRequest_VariableDefinitions#40), the value of `cell_measures` for a number of variables in the [CMIP6_SImon.json](https://github.com/PCMDI/xml-cmor3-database/blob/master/src/CMIP6_SImon.json) MIP table is equal to `--MODEL`, e.g. [siforcecoriolx](https://github.com/PCMDI/xml-cmor3-database/blob/master/src/CMIP6_SImon.json#L680). Would it be possible for CMOR to handle `cell_measures` with a value of `--MODEL`?

**Comment by taylor13** [comment]
@ehogan Hi Emma,  Do you know:   has --MODEL replace --OPT (and @OPT) as the way to indicate that cell_measures is optional (depending on the model formulation)?  Or is it *required*, but whether areacella or areacello or areacell?? should be assigned to the attribute depends on the model?  I'm sure Martin must have documented this, but I can't find it.

**Comment by ehogan** [comment]
@taylor13 both `--MODEL` and `--OPT` are separate, valid options (see http://clipc-services.ceda.ac.uk/dreq/u/ATTRIBUTE::structure.cell_measures.html). I'm afraid the only documentation I know of are the links Martin posted on cmip6dr/CMIP6_DataRequest_VariableDefinitions#40.

**Comment by dnadeau4** [comment]
I modified cmor and add --MODEL in the cell_measures options. 
https://github.com/PCMDI/cmor/commit/6a0f8f06c31c0a62e9246d7551afe7c59e5685b4

**Comment by jkettleb** [comment]
Can I check I understand the consequences of this?  I think the MIP tables will currently omit `cell_measures` when they are `--MODEL` or '--OPT` in the data data request.  So the NetCDF written from CMOR will not have `cell_measures` for these variables.

This may be the most pragmatic thing to do - as dealing with `--MODEL` and `--OPT` in CMOR may be require effort and we are short of effort.  I think the impact on end users isn't too big either - they will work round it.  BUT I think it also means any QC for publication will need to be suitably relaxed about the `cell_measures`.  Who determines the QC policy for publication?  Do we need agreement?

**Comment by taylor13** [comment]
@jkettleb Yes, CMOR will omit attaching cell_measures to variables where --MODEL or --OPT has been specified.  The publication QC is largely based on PrePARE, which performs the same checks on global attributes as CMOR.  In general it doesn't check variable attributes (like cell_measures), so files written by CMOR are guaranteed to pass the publication QC, but files written by other software may pass the publication QC but still be non-compliant with some of the CMIP6 specs.  We plan to work to make PrePARE more comprehensive, but that won't happen very soon.

By the way, the reason we don't define cell_measures for the --Model and --OPT cases is because cell_measures (like areacella and areacello) in all models I know of only apply to variables that are carried on the grid cell centers (not their edges or vertices, as ua and va normally are).  So CMOR is generally doing the write thing *not* pointing to a cell_meaure for the --MODEL and --OPT cases.  Make sense?

**Comment by jkettleb** [comment]
Thanks @taylor13 that makes sense.  I'm not sure  I understand why the data request doesn't just omit `cell_measures` in these cases - but I think I can live with that uncertainty.

Is PrePARE the QC developed at DKRZ - I think BADC see the DKRZ tool as the most likely QC tool.  (Sorry google search on PrePARE wan't very helpful)

**Comment by taylor13** [comment]
@jkettleb - I think Martin uses the cell_measures for two purposes: to indicate what variable contains grid cell areas *and* to indicate requirements as to whether values should be reported at cell centers or not.  Martin provides some explanation here: https://www.earthsystemcog.org/projects/wip/drq_interp_cell_center 
PrePARE has only been recently named ("Pre-Publication Attribute Reviewer for the ESGF").  This and the CF-checker will be executed as part of the ESGF publication process.  PrePARE is also run as part of CMOR, so that data providers using CMOR can be assured their data is publishable.  The DKRZ QC tool will perform additional checks of output but will not be included as part of the publication job stream.   As I understand it, the DKRZ tool *includes* PrePARE to check the metadata, so if you run it, you also will be assured that the files can be published on ESGF.  The DKRZ tool might also be run on files after they've been published so that problems can be identified without slowing the publication job stream.

**Comment by jkettleb** [comment]
Thanks for you time on this @taylor13.  That documentation on cell_measures helps clarify things.
Thanks for the notes on the QC checking.

**Comment by dnadeau4** [comment]
Fix in 3.2.2
