### ISSUE TITLE
Loading more than 10 tables results in segfault

### ISSUE THREAD

**Issue by goord** [PCMDI/cmor#152]
Whenever I try to cmorize a set of variables that require more than 10 (CMOR_MAX_TABLES) tables to be loaded, the application ungracefully crashes with a segmentation error. There should be a check in cmor_tables.c line 547 to make sure cmor_ntables does not exceed the array bounds. Apart from that, I was wondering why the limit is set so low, as the number of cmip6 tables is a multiple of this. Moreover, there is no way to 'unload' a table.

**Comment by dnadeau4** [comment]
@goord the first developer of CMOR put the tables on the STACK and not on the HEAP.   Tables are getting very big and you run out of memory.    I never load more than 2 to 3 tables at once to get my variables.    Why do you need that many?

**Comment by goord** [comment]
We are post-processing and rewriting EC-Earth output to CMIP6 compliant data for the PRIMAVERA project. The data request spans around 25 tables, and I am running CMOR-python in a single program for all of them. I can split up the data request in multiple chunks of <10 tables though.

**Comment by dnadeau4** [comment]
TravisCI and circleCI only allows 3G on their virtual machine for Continuous Integration.  I am not sure I can load that many tables in one of my tests on their machine.  I think you should split your program in different `realm` for stability.  I can change the code so that there is no segmentation fault, but I should not to re-architect CMOR entirely at this point.   

BTW,  I have just finished implementing more required attributes for CMIP6 for `parent_experiment_id` and `sub_experiment_id`.  Just giving you the heads up about what to expect.

**Comment by dnadeau4** [comment]
Actually I was able to read 30 tables in.  So I will make the changes to read a maximum of 30 tables.  Hopefully that will help you.  I also got rid of the segmentation fault.

**Comment by goord** [comment]
Great, thanks! Will this change also appear in the anaconda package?

**Comment by dnadeau4** [comment]
I used to have a daily update for my branch.  I can re-trigger and let you know when it is ready.

**Comment by dnadeau4** [comment]
You can get the latest and greatest.... Note that you will get the nightly development version, so I created a new environment that you need to activate.   This way you don't break your current environment. 

`conda create -n nightly -c pcmdi/label/nightly -c conda-forge cmor`
`source activate nightly`
