### ISSUE TITLE
Missing "frequency" in cmor table

### ISSUE THREAD

**Issue by svalcke** [PCMDI/cmor#165]
Hi,
I have a problem using PrePARE to validate one of my output file containing hourly data. I realise that the frequency listed in the cmor table CMIP6_CV.json are only:
"frequency":[
            "3hr",
            "6hr",
            "day",
            "fx",
            "mon",
            "monClim",
            "subhr",
            "yr"
while the ones in the CMIP6 table CMIP6_frequency.json are:
"frequency":[
        "1hr",
        "1hrClimMon",
        "3hr",
        "3hrClim",
        "6hr",
        "day",
        "decadal",
        "fx",
        "mon",
        "monClim",
        "subhr",
        "yr",
        "yrClim"
Shouldn't the cmor table CMIP6_CV.json be updated?
Thanks,
  Sophie

**Comment by durack1** [comment]
@dnadeau4 @taylor13 these should be generated using the [CMIP6_CVs/CMIP6_table_id.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_table_id.json) file each time the `CMIP6_CV.json` file is created

**Comment by taylor13** [comment]
@dnadeau4 Are you now using the current frequency CV?  If so, you can close this issue.

**Comment by dnadeau4** [comment]
I changed the `CMIP6_CV.json` to use the [CMIP6_CVs/CMIP6_frequency.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_frequency.json).   The list describe by @svalcke was remaining from the first version of `CMIP6_CV.json` creation, (before @durack1 scattered it in many pieces.)  My script was superseding the frequencies coming from WCRP repository file.  Thanks to @svalcke for finding this!

**Comment by durack1** [comment]
@dnadeau4 this seems to be a good time to double check the other downstream dependencies from CMIP6_CVs..

**Comment by dnadeau4** [comment]
@durack1 Will do.  There might be other dictionary left over from previous version.

**Comment by dnadeau4** [comment]
@durack1 Your [CMIP6_license.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_license.json) is different than [CMOR](https://github.com/PCMDI/cmor/blob/master/TestTables/CMIP6_CV.json#L933-L935)  since I am using a `regular expression` to match it.  If you ever change it that change will not appear in CMOR CMIP6_CV.json.  

As well, your [mip_era.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/mip_era.json) has many option and `CMOR` [CMIP6_CV.json](https://github.com/PCMDI/cmor/blob/master/TestTables/CMIP6_CV.json#L936-L938) is set to `CMIP6` only.

**Comment by taylor13** [comment]
for mip_era, we want CMOR to be more restrictive than the CV allows, so I think we can't simply import the CV.

For the license, we don't expect it to change, so no worries (I guess).  Maybe we should modify the syntax of the CV to allow CMOR to ingest it????   This would be a very low priority in my view.

**Comment by dnadeau4** [comment]
Fixed in 3.2.4
