### ISSUE TITLE
time_range in filename not constructed correctly

### ISSUE THREAD

**Issue by jonseddon** [PCMDI/cmor#178]
Hi,

Two issues have been spotted in the time_range segment of filenames:

* The components included are not always correct for the specified frequency, e.g.:

`ua7h_E3hrPt_HadGEM3-GC31-LM_highresSST-present_r1i1p1f1_gn_19500101030000-19501230210000.nc` (should be `yyyyMMddhhmm` rather than `yyyyMMddhhmmss`)

Other files are named correctly:
`rsdscs_3hr_HadGEM3-GC31-LM_highresSST-present_r1i1p1f1_gn_195001010130-195012302230.nc`

I think that this is due to the interval not being calculated correctly at https://github.com/PCMDI/cmor/blob/master/Src/cmor.c#L5435. In a file at a frequency of 1hr, with all of the time coordinate points correctly spaced at 3600 second intervals, interval was assigned the value of 1499.99. I don't think that this is a problem with our model data as I have seen the same problem with files generated by another institution. I haven't been able to work out why `cmor_convert_interval_to_seconds()` returns the wrong value.

* The seconds in the time_range string are always rounded down, rather than to the nearest second. Other tools that work with netCDF data round to the nearest second and so the times in the filenames don't match the times reported by other tools, e.g.:
`prc_E1hr_HadGEM3-GC31-LM_highresSST-present_r1i1p1f1_gn_19500101002959-19501230233000.nc`

where the first time is 1950-01-01 00:29:59.99993.

I've got a fix for these and will raise a PR shortly.

Thanks,

Jon

**Comment by durack1** [comment]
@jonseddon thanks for this.. If there was a way to attempt to ensure that most of the MOHC contributed data starts in January and ends in December for the contributed years that would make life considerably easier for a user compared to CMIP5.. Just a user comment, unrelated to this issue

**Comment by taylor13** [comment]
@dnadeau4 @jonseddon :  Just to confirm that the precision required by CMIP6 for different frequencies can be found in table 2 of https://docs.google.com/document/d/1h0r8RZr_f3-8egBMMh7aqLwy3snpD6_MrDz1q8n5XUk .  For 3hr data, we require yyyyMMddhhmm (no seconds), as in the 2nd example above.

**Comment by dnadeau4** [comment]
@jonseddon WOW!  This is awesome,  thanks for the code!   I'll run my tests with it and if filenames are fine, then I will merge.   (I'll let @doutriaux1 and @taylor13 check before)

**Comment by taylor13** [comment]
This code looks much cleaner. Thanks, @jonseddon .  I'm still concerned about truncation problems.  Here's the behavior we want:

Non-climatological fields: Label with first and last time coordinate values in file

decadal and yr:  	YYYY
mon: 			YYYYmm
day:			YYYYmmdd
6hr, 3hr, 1hr:		YYYYmmddhhmm   
but note that time values should first be rounded to the nearest minute before converting to component time
subhr:			YYYYmmddhhmmss 
but note that time values should first be rounded to the nearest second before converting to component time

Climatological fields: Label with first bound of first time coordinate and last bound of last time coordinate found in file.

monclim:		YYYYmm 
but note that in the case of the end time, 1960-01-01 00:00:00 should appear as 195912 (not 196001) and if truncation errors lead to a start time like 1958-12-31 23:59:59, this should appear in the file name as 195901 (not 195812).

1hrClimMon:		YYYYmmddhhmm
				but round seconds to nearest minute before converting to component time.
  	
I’m checking for confirmation from Martin but I don’t think 3hrClim is needed for CMIP6.

Please check that CMOR3 handles all of the above cases correctly.

**Comment by taylor13** [comment]
to be sure, the "rounding" steps in the above might not be necessary if it is already done by the component time function.  The reason rounding might be necessary is to avoid truncation error issues.   For example, in frequency="day" files, we don't want a time of 0.9999999999 days since 1960-01-01 0:0:0 to be recorded in file names as "19600101", but rather as "19600102".

Depending on how component time function is coded, you might get what we want by adding to the times passed to component time  30 seconds in the case of frequencies 6hr, 3hr, 1hr, and 1hrClimMon; and 0.5 seconds in the case of subhr.

For monClim you could probably safely subtract 30 seconds from the end time and add 30 seconds to the start time to make sure you get the right month.

Since I don't know how component time works, the above might be wrong and not give us what we want.

**Comment by jonseddon** [comment]
Thanks for the feedback! I'm afraid that I had a long weekend due to a public holiday. I'm just adding some tests to make sure that the behaviour is as desired. I'll push to the PR when everything's complete.

**Comment by taylor13** [comment]
Martin confirms that 3hrClim is not needed for any MIPs we know of.  Perhaps it is needed by obs4MIPs?

**Comment by taylor13** [comment]
Also, the controlled vocabulary for frequency currently includes "decadal", but this will very likely get change shortly to "dec".

**Comment by jonseddon** [comment]
Hi,
The code is (hopefully!) finished now and I've written a series of tests to demonstrate the behaviour requested by @taylor13.

The tests required a couple of changes to the test tables to work. These are covered by the following issues:
https://github.com/WCRP-CMIP/CMIP6_CVs/issues/338
https://github.com/PCMDI/cmip6-cmor-tables/issues/67
https://github.com/PCMDI/cmip6-cmor-tables/issues/68

Thanks,

Jon

**Comment by taylor13** [comment]
@jonseddon   
I noticed in the example for testing decadal output that the time units are defined as "years since ...".

A "year" is not a true unit, since it sometimes represents 365 days and sometimes 366.  In CMIP we do not allow this unit.  The "time" should be expressed as "days since ...."    
Not sure this affects the test case, but wanted everyone to be aware of this.

**Comment by taylor13** [comment]
Could you point me to the C code where the time label is constructed?   It might be good for a 2nd pair of eyes to look over it before releasing.

**Comment by dnadeau4** [comment]
https://github.com/jonseddon/cmor/blob/2d2f85a526de45e9c07f5ddc54ca783d61c26288/Src/cmor.c#L5408-L5722

**Comment by jonseddon** [comment]
@taylor13 Thanks for the feedback on the units. I have changed those to `days since` now.

**Comment by dnadeau4** [comment]
Releasing today please test and close issue.

**Comment by jonseddon** [comment]
@dnadeau4 Brilliant, thanks for that. All of the tests are passing and it's looking good on real data too. Many thanks!

**Comment by wachsylon** [comment]
I have an additional question.
There are variables requested for sub-daily frequencies (6hr,3hr,1hr) and with `cell_methods = time:mean` . The file name of such variables is created using the time value instead of the time bound. Is that correct?
For example, there are files for three hour frequency:
`*195101010130-195112312230.nc`
however time bounds would cover
`*195101010000-195201010000.nc`

**Comment by taylor13** [comment]
All files except those containing climatologies rely on the time coordinate values (rather than the time cell bounds) in constructing the file name.  The precision provided in time-labels depends on the frequency:
```
for yr and dec: year only (e.g., 2004)
for mon: year and month only (e.g., 200401)
for day: year, month, and day only (e.g., 20040101)
for 6hr, 3hr, and 1hr: year, month, day, hour, and minutes only (e.g., 200401010130)
for subhr: year, month, day, hour, minutes, and seconds (e.g., 20040101000730 = 2004 Jan 1 00:07:30)
```
So, I think your time label looks correct .

**Comment by wachsylon** [comment]
Great, thank you very much!
