### ISSUE TITLE
Sign convention on evaporation fluxes

### ISSUE THREAD

**Issue by martinjuckes** [PCMDI/cmor#207]
I've had a query on the data request about the variable evspsbl, which has standard name water_evaporation_flux. The question is whether it should have a "positive" attribute set in the MIP tables? ([214](https://github.com/cmip6dr/CMIP6_DataRequest_VariableDefinitions/issues/214))

I believe the answer is that it should not be set, because sign convention is implicit in the standard name .. is this correct?

**Comment by dnadeau4** [comment]
I remember for `rsut` `TOA Outgoing Shortwave Radiation` we needed `positive=up` for some people reverse their axis which changes the sign of the data (-/+).   

@taylor13 what do you think?

**Comment by durack1** [comment]
@martinjuckes @dnadeau4 @taylor13 I think having the "positive" attribute set is a good idea, for [`evs`](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_Omon.json#L1234) and ['wfo'](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_Omon.json#L4960) (along with similar variables e.g. `wfonocorr` etc this would also be a good idea

**Comment by taylor13** [comment]
The specs for CMIP5, found at  http://cmip-pcmdi.llnl.gov/cmip5/docs/CMIP5_output_metadata_requirements.pdf  , state:

"The positive direction of vertical fluxes must be consistent with that specified in the “positive” column (O) of the CMIP5 Requested Output table and is also indicated by the standard_name (e.g., "surface_upward_latent_heat_flux” and "surface_downward_eastward_stress"). "

The information is only suppled for the vertical direction and not for variables where only one direction is possible (e.g., vertical velocity in the atmosphere = dz/dt has to be positive up because z is defined as positive up).   This "direction" indication in the data request is needed to enable CMOR to reverse the sign (when appropriate) since CMOR can't parse the standard_names.

**Comment by martinjuckes** [comment]
Thanks, I'll set it for all upward/downward/incoming/outgoing/upwelling/downwelling fluxes and stresses. This includes fluxes of heat, momentum (stress and the Eliassen Palm flux), composition (O2, CO2, DMS, salt, H2O).

I'm not sure about Paul's suggestion of adding it for wfo and wfonocorr. These are water fluxes into the ocean, including flux from land to ocean, so some of the flux would be considered as horizontal in the climate model. But really it depends on how CMOR is used: is there a need for "positive=down" for water fluxes into the ocean?

**Comment by taylor13** [comment]
I was sort of wondering about wfo too for the same reason.  But of course, run-off is in fact spread over the grid cell and enters through the top of the grid cell (so vertically).  Anyway, let's definitely include the vertical fluxes you list (plus, convective mass flux).  I think we can omit wfo and similar.

For any variable where the DREQ has specified a value for "positive", CMOR requires users to say whether the data they're giving CMOR assumes "positive is up" or "positive is down".  If the user's direction is opposite what is requested by DREQ, CMOR multiplies the data by -1 before storing it, so that it will conform with the specifications.

**Comment by martinjuckes** [comment]
Thanks .. I've copied Karl's description above into the data request so it should appear here: http://clipc-services.ceda.ac.uk/dreq/u/ATTRIBUTE::CMORvar.positive.html in release 01.00.16

**Comment by taylor13** [comment]
To be sure ... I assume you aren't changing the structure of your data base, just adding a description, right?

**Comment by martinjuckes** [comment]
Correct .. every attribute has a description tag, but this one was previously an empty string, now it has meaningful content.

**Comment by taylor13** [comment]
Excellent.  The description should be helpful.

**Comment by taylor13** [comment]
Denis,
I think this probably can be closed.  Do you agree?
Karl
