### ISSUE TITLE
Dataset version of cmorized files

### ISSUE THREAD

**Issue by pabretonniere** [PCMDI/cmor#210]
Hello,

This might be more a convention/DRS issue than a CMOR one, but we noticed that the version (last level of the CMOR directory tree) is hard coded in CMOR as the date of the creation of the file. 

That leads to files having different versions if you start the CMORization for example at 11.59pm even if they belong to the same "batch" of original files and the same "cmorization run". That makes the post-processing of these files harder because you can't know the version of the files by default and creates different versions of a single dataset.

Could the version/date be set as the beginning of the CMORization? Or passed as an argument of cmor_setup?

Thank you,
Best regards,

Pierre-Antoine Bretonnière

(Tagging my colleague @jvegasbsc who is working on this so he can follow)

**Comment by taylor13** [comment]
Thanks for pointing out this issue.  I think it is o.k. (if not ideal) that different variables will be labeled with a different version number in the directory structure, depending on the day they are written, but I don't think the collection of files containing output of a single variable should be split among different directories.  I presume if you wrote a file containing surface temperature data for years 1850-1900 just before midnight, and then you wrote a second file with surface temperature data for years 1901-1950 after midnight, those files would be placed by default in two different directories by CMOR.  That would not be good.

The easiest fix would be to require the user to specify a nominal date defining the version.  Maybe there shouldn't even be a default value assigned by CMOR.  Opinions?

We should check with the ESGF folk and determine whether there are implications for ESGF publishing.

**Comment by durack1** [comment]
@pabretonniere @taylor13 I think **hardcoding** a version/date is a bad idea, as this same `version` info will then be maintained irrespective of when files are written. I can see some utility in setting a CMOR instance `version`, so while the program is executing it maintains the same `version` tag persistent to that execution instance.

This will be highly variable across different uses of CMOR I'd think, as it really depends how the program is being called

**Comment by taylor13** [comment]
I think having the files that comprise a single dataset split across directories is a bad idea.  Would cdspan be able to create an xml for the dataset?  The files might not be produced by a single run of CMOR, so how would you have cmor place these in the same directory if run on different days?

**Comment by durack1** [comment]
@pabretonniere in your use case for CMOR, how do you call the software when writing multiple variables (from a single simulation) across a single executing instance?

**Comment by pabretonniere** [comment]
Hi. 

Thanks for your comments. 

We are using the ece2cmor suite (python, https://github.com/goord/ece2cmor3), which does the cmor_setup and then, does a loop on the input files to read the variables one by one and write them with cmor.

The thing is that the CMORization is integrated in our workflow and that it is done on the HPC each time we have a chunk of simulation (usually between 4 months and 1 year of simulation), so even for one variable/one simulation, we will call the cmorization several times (at a few hours of interval) and end up having, as @taylor13 said, for example tos for 1850-1900 in a directory and tos 1900-1950 in another one. That is why I was hoping we could have a version passed as an argument of cmor setup for example to fix it for the whole simulation.

**Comment by dnadeau4** [comment]
@pabretonniere I think you should be able to use CMOR to append to a file and write more data.  I don't know if this functionality still work.

**Comment by dnadeau4** [comment]
You can also use NCO, "ncrcat" to concatenate files, but you will have to manage the filename yourself.  PrePARE will make sure that the filename timestamps matches [first_time, last_time] in your "time" variable.    @taylor13 maybe it is time to add ".suffix" back...

**Comment by taylor13** [comment]
We don't want folks concatenating files as part of normal procedure in CMIP6.  

I note the following:
1)  The CMIP6 specs say the lowest level sub-directory should be <version>, indicating *approximate* date of model output file.  So date doesn't have to be the actual date the file is written.
2)  Sasha tells me the ESGF publisher will not (without additional coding) be able to handle an "atomic" dataset that is split into more than one sub-directory, so we really would like to prevent this from happening.
3)  Users I think will prefer if all files in an "atomic" dataset are co-located in the same sub-directory.

So we must make it possible for the data provider to put all files belonging to a single dataset into a single subdirectory.  Denis says to override the default behavior (defining a directory with the version based on the date at the time the file is written) by replacing in the user_input.json file the following lines:

```
"#output_path_template":"Template for output path directory using tables keys or global attributes",
"output_path_template":"<mip_era><activity_id><institution_id><source_id><experiment_id><_member_id><table><variable_id><grid_label><version>",
```
to
```
"_myversion":"v20170725",
"#output_path_template":"Template for output path directory using tables keys or global attributes",
"output_path_template":"<mip_era><activity_id><institution_id><source_id><experiment_id><_member_id><table><variable_id><grid_label><_myversion>",
```
Since it is essential that all files in a single dataset be in the same sub-directory, we should have CMOR provide a "warning" if in the directory tree for that dataset another "version sub-directory" already exists (other than the one the data provider is writing to).    Sometimes this would indicate that a previous version of the data set existed, so the data provider would ignore the warning.  But if the data provider got the warning because they were relying on CMOR's default behavior of creating the subdirectory with the current date (even though files in the same dataset were written on earlier dates, then hopefully the data provider would override the default.

Also, we should discourage data provider's from overriding the CMOR default of "preserve" when writing files.  If the user tried to write data to a sub-directory with an older version of the dataset, CMOR will error exit if the the files already exist, so the user would know they should create a new version label (presumably with a later date).

**Comment by pabretonniere** [comment]
I was indeed going to say that with the size of the outputs, concatenating the files was not going to be efficient. We tried to use the replace mode but it wasn't useful as the version was changing. 

We will go for now with @taylor13 's suggestion of modifying the user_input.json, that will solve our issue. Thanks a lot! But that would indeed be nice to have in the next release of CMOR a warning saying that we already have a subdirectory with a different version.

**Comment by taylor13** [comment]
by the way, I think it is best to include an underscore in front of the variable you're defining for the version number (e.g., "_myversion").  The underscore indicates this is an internal CMOR variable which won't be written to output files.

**Comment by taylor13** [comment]
@pabretonniere Did you notice my previous comment?  without the underscore, I think a global attribute named myversion will get written to your files.  I don't think we want that.
thanks.

**Comment by pabretonniere** [comment]
@taylor13 yes, sorry I didn't reply, I indeed used _myversion and it works well. Thank you!
