### ISSUE TITLE
Updates in support of CMIP6

### ISSUE THREAD

**Issue by durack1** [PCMDI/cmor#22]
@taylor13 @doutriaux1 I've included an email from Martin Juckes below which outlines some key items for consideration in CMOR updates in preparation for CMIP6:

```
-----Original Message-----
From: "martin.juckes"
Date: Thursday, April 23, 2015 at 2:07 AM
To: "Paul J. Durack"
Cc: "Taylor, Karl Taylor", "Doutriaux, Charles"
Subject: RE: CMIP6 and CMOR2+

Hello Paul,

Glad to meet you.

Please don't start on the OMDP document yet -- that is input into the process, and we need to agree on how the tables etc will be organised in CMIP6 to deal with the expanded structure. I was planning on providing you with CMOR format MIP tables when we have mature documents.

At the moment the CMOR/CMIP6 issues that I'm aware of are:
(1) Need to support polar stereographic grids. Charles has said in an email that the code is there -- but I'm not sure what needs to be done in the MIP tables;
(2) Extend the "Conventions" attribute: pending agreement from CF committee -- and add a MIP table tag so that some variables can have "UGRID-0.9" added to the conventions attribute;
(3) Add a resolvable unique identifier: Tobias Weigel (DKRZ) is working on a system of resolvable identifiers (using the Handle Registry -- www.handle.net). Has he been in touch with you? I'll be at a meeting of one of the European project which is supporting his work next week, and I hope to find out more about his plans there.
(4) Global attributes: the WIP (WGCM Infrastructure Panel) is discussing a range of changes to global attributes -- hopefully these will not be difficult to implement;
(5) Delivering output in a flat directory structure: it currently provides a pseudo-ESGF directory structure with the result that some groups did not bother to transform to a correct directory structure.
(6) There is demand for a more robust system of testing CMOR and associated CMIP6 tables. We may be able to provide some support on this -- I'll check the status of our discussions there.
(7) Lots of new variables and dimensions -- but hopefully these will not need software changes.

For the CMIP6 data request I have a discussion board (http://dreq01.vanillaforums.com) and I have started a "CMOR" section -- we can move this somewhere else if you have a more convenient location (at the moment this board is mainly used by me to keep track of data request issues, so there is not much content).

regards,
Martin
```

**Comment by durack1** [comment]
@doutriaux1 @gleckler1 @taylor13 @dnadeau4 @durack1 - we're all pinged for CMIP6/CMOR3

**Comment by dnadeau4** [comment]
[ ] Need to support polar stereographic grids. Charles has said in an email that the code is there -- but I'm not sure what needs to be done in the MIP tables;
* Not supported!

[x] Extend the "Conventions" attribute: pending agreement from CF committee -- and add a MIP table tag so that some variables can have "UGRID-0.9" added to the conventions attribute;

[]Add a resolvable unique identifier: Tobias Weigel (DKRZ) is working on a system of resolvable identifiers (using the Handle Registry -- www.handle.net). Has he been in touch with you? I'll be at a meeting of one of the European project which is supporting his work next week, and I hope to find out more about his plans there.

[x] Global attributes: the WIP (WGCM Infrastructure Panel) is discussing a range of changes to global attributes -- hopefully these will not be difficult to implement;

[x] Delivering output in a flat directory structure: it currently provides a pseudo-ESGF directory structure with the result that some groups did not bother to transform to a correct directory structure.

[x] There is demand for a more robust system of testing CMOR and associated CMIP6 tables. We may be able to provide some support on this -- I'll check the status of our discussions there

[x]Lots of new variables and dimensions -- but hopefully these will not need software change

**Comment by gleckler1** [comment]
@dnadeau4   gleckler1 has not yet heard from T. Wiegel but good to know about this.   We do need to think through a robust directory structure for obs4MIPs.   For obs4MIPs, there are a few datasets (mostly snow and ice related) where polar stenographic is needed but that could come with a second release.

**Comment by dnadeau4** [comment]
@TobiasWeigel @gleckler1 I think my list above is pretty good.  I am not sure if we need more information on Conventions using "UGRID-0.9".  Right now Conventions is specified in the "CMIP6_xxxx.json" tables.

**Comment by durack1** [comment]
@dnadeau4 do you mean `controlled vocabulary` rather than `Conventions` above - and I'm thinking the https://github.com/WCRP-CMIP/CMIP6_CVs repo specifically here

**Comment by dnadeau4** [comment]
There is a Conventions attributes that is set to         ```"Conventions": "CF-1.6 CMIP-6.0"``` in [CMIP6_Amon.json](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_Amon.json)

**Comment by dnadeau4** [comment]
Only the Conventions seems to be an issue since it is hard coded in the table.   Is this good enough?

**Comment by gleckler1** [comment]
@dnadeau4 @durack1 working on obs4MIPs directory structure now.   Does the above question on conventions apply to both CMIP and obs4MIPs?

**Comment by dnadeau4** [comment]
What append to Conventions?  Is it good enough the way it is right now?

**Comment by durack1** [comment]
@dnadeau4 this is a question for @taylor13

**Comment by taylor13** [comment]
will check

**Comment by dnadeau4** [comment]
@taylor13 is Conventions still good as: `"Conventions": "CF-1.6 CMIP-6.0"`
`

**Comment by dnadeau4** [comment]
@taylor13 Do you have an answer about `Convention`?

**Comment by dnadeau4** [comment]
Most of this ticket has been resolved except Convention,  I will close it and we can reopen a new one.
