### ISSUE TITLE
API documentation out of date

### ISSUE THREAD

**Issue by alaniwi** [PCMDI/cmor#242]
From the source it seems that the argument `suffix` has been dropped from the call list of `cmor_write()` in 3.x (since 2.x), but in https://cmor.llnl.gov/mydoc_cmor3_api/#cmor_write it is still shown as being there.

I have no idea whether this is the only instance or one of many. I just discovered this while trying to compile CDO against CMOR3, which was evidently written for CMOR2, and the compile fell over with wrong number of arguments in the call to `cmor_write` but the docs don't show the change.

**Comment by taylor13** [comment]
the documentation is definitely out of date with respect to "suffix".  Anyway for CMIP6 "suffix" is not needed because the file name is completely generated by CMOR based on an input template and certain global attributes.

**Comment by alaniwi** [comment]
Fair enough. I'm not yet familiar enough with it to really comment - I'm basically just trying to compile software packages, and just letting you know an issue I stumbled on.

**Comment by taylor13** [comment]
yes, thanks very much for that.  Keep raising issues you encounter, so we can improve the software and documentation.

**Comment by dnadeau4** [comment]
This has been fixed in 3.2.8 and I have a test for it.  I expect 3.2.8 to be released by the end of the month. 

https://github.com/PCMDI/cmor/blob/e67d8b014a5ad931fcac1dfdb10da28d2599208e/Test/test_python_appending.py

You could try to use the nightly build.
`conda install -c pcmdi/label/nightly -c conda-forge cmor `

Here is the commit
https://github.com/PCMDI/cmor/commit/e67d8b014a5ad931fcac1dfdb10da28d2599208e
