### ISSUE TITLE
PrePARE crashes when setting 'branch_time_in_child'

### ISSUE THREAD

**Issue by senesis** [PCMDI/cmor#306]
I Just installed CMOR and tables using https://cmor.llnl.gov/mydoc_cmor3_conda/
Launching PrePARE as
``
PrePARE .../cmip6-cmor-tables/Tables areacella_fx_CNRM-CM6-1_amip_r99i1p1f2_gr.nc
``
Got :
_Traceback (most recent call last):
  File "/home/gmgec/mrgu/senesi/miniconda2/envs/cmor/bin/PrePARE", line 11, in <module>
    load_entry_point('CMOR==3.3', 'console_scripts', 'PrePARE')()
  File "/home/gmgec/mrgu/senesi/miniconda2/envs/cmor/lib/python2.7/site-packages/cmip6_cv/PrePARE/PrePARE.py", line 724, in main
    sequential_process(source)
  File "/home/gmgec/mrgu/senesi/miniconda2/envs/cmor/lib/python2.7/site-packages/cmip6_cv/PrePARE/PrePARE.py", line 633, in sequential_process
    checker.ControlVocab(ncfile)
  File "/home/gmgec/mrgu/senesi/miniconda2/envs/cmor/lib/python2.7/site-packages/cmip6_cv/PrePARE/PrePARE.py", line 469, in ControlVocab
    if not isinstance(self.dictGbl['branch_time_in_child'], numpy.float64):
KeyError: 'branch_time_in_child_'

Did I miss some key point in install ?
I send the file separately to  @durack1  and @dnadeau4

**Comment by taylor13** [comment]
For AMIP simulations (like this one), there is no "parent", so branch_time_in_child can either be omitted as a global attribute (which is the preferred options) or set to the start time of the run.  Perhaps PrePARE hasn't encountered this case before???

In any case the error message isn't very explicit about what the problem is (or maybe I just don't understand python-speak).

**Comment by senesis** [comment]
Just shaking (I mean re-setting) my environment made the problem disappear
Thanks . Sorry for the noise

**Comment by dnadeau4** [comment]
@taylor13 if `branch_time_in_child` is not there PrePARE will fail.  I was asked to check if it is `double`.  I thought it was defaulted to "0.0".

**Comment by taylor13** [comment]
I'll reopen this and we can discuss next week whether we need to do something.  Apparently @senesis solved his immediate problem.

There are several global attributes that must be present *if* there is a parent, but may otherwise be omitted.  Next week we can check whether revisions are needed when PrePARE checks these attributes.

**Comment by senesis** [comment]
I agree the issue should be reopened : it occurs because my amip data do not have attribute branch_time_in_child while PrePARE (or the Tabe describing amip expt) thinks it must have one
The [CMIPS6 CV document](https://docs.google.com/document/d/1h0r8RZr_f3-8egBMMh7aqLwy3snpD6_MrDz1q8n5XUk/edit) allows for omitting branch times when there is no parent

**Comment by dnadeau4** [comment]
@senesis fix in the PrePARE branch.
https://github.com/PCMDI/cmor/commit/6157a673dc1f9233fc3ca3d3c6908b31ef30cd98

**Comment by dnadeau4** [comment]
https://github.com/PCMDI/cmor/commit/2c07f87edfb864cb2c63788bf598119a0629824e
