### ISSUE TITLE
PrePARE exit status

### ISSUE THREAD

**Issue by jonseddon** [PCMDI/cmor#316]
Hi,

This is similar to #284. With CMOR 3.3.1 I can use the following session to reproducibly get a return code of 0:

```
$ PrePARE Tables/CMIP6_Amon.json tas_Amon_HadGEM3-GC31-LM_highresSST-present_r1i1p1f1_gn_195001-195012.nc 
Processing: /some/dir/tas_Amon_HadGEM3-GC31-LM_highresSST-present_r1i1p1f1_gn_195001-195012.nc


*************************************************************************************
* This file is compliant with the CMIP6 specification and can be published in ESGF  *
*************************************************************************************

$ echo $?
0
$ ncatted -a branch_time_in_child,global,m,c,"15" tas_Amon_HadGEM3-GC31-LM_highresSST-present_r1i1p1f1_gn_195001-195012.nc
$ PrePARE /home/h04/jseddon/primavera/cmip6-cmor-tables/Tables/CMIP6_Amon.json tas_Amon_HadGEM3-GC31-LM_highresSST-present_r1i1p1f1_gn_195001-195012.nc 
Processing: /some/dir/tas_Amon_HadGEM3-GC31-LM_highresSST-present_r1i1p1f1_gn_195001-195012.nc


=====================================================================================
branch_time_in_child is not a double:  <type 'str'>
=====================================================================================


*************************************************************************************
* Error: The input file is not CMIP6 compliant                                      *
* Check your file or use CMOR 3.x to achieve compliance for ESGF publication        *
*************************************************************************************

$ echo $?
0
```

If I have a critical error then I do get a return code of 1, but for this not compliant error I always get a return code of 0. A return code of 1 (or something else non-zero) would be useful to allow us to integrate PrePARE into our pre-publication checks without parsing the output.

Thanks,

Jon

**Comment by dnadeau4** [comment]
That functionality was lost when @glevava parallelized PrePARE.  I can put it back for the `sequential` section.  Not sure how to handle the parallel one since the process return a logfile. 

I will try to use the `cmip6_cv.get_CV_Error()` function and see if that does the trick.

**Comment by dnadeau4** [comment]
This has been fixed in PrePARE. 
https://github.com/PCMDI/cmor/pull/318/commits/b6eee148336a0bca44f4fcc019fb3689e5b97513

**Comment by jonseddon** [comment]
Brilliant, thanks @dnadeau4 for adding this!

**Comment by glevava** [comment]
Unfortunately, `cmip6_cv.get_CV_Error()` shouldn't be use here ([https://github.com/PCMDI/cmor/blob/e560228f28e6e6cf37aff78dbfb6a88f2701b8fe/LibCV/PrePARE/PrePARE.py#L595](https://github.com/PCMDI/cmor/blob/e560228f28e6e6cf37aff78dbfb6a88f2701b8fe/LibCV/PrePARE/PrePARE.py#L595)). The "table memory" issue appears again despite my PR... 
I removed a lot of `cmip6_cv.set_CV_Error()` into PrePARE as it persist error = 1 for all scanned files since one of them actually has an error.
I agree that consequently the return code by PrePARE is always 0 whatever an error is raised or not. I can think about it in another PR.

In addition, different return codes could be useful to distinguish when only one / several / all files has a CV error.

**Comment by glevava** [comment]
Fixed with [https://github.com/PCMDI/cmor/pull/322](https://github.com/PCMDI/cmor/pull/322)
