### ISSUE TITLE
CMOR 3.3.2 and libssh2

### ISSUE THREAD

**Issue by anfab** [PCMDI/cmor#337]
I've just upgrated cmor from 3.2.4 to 3.3.2.

Importing cmor in python results in the following error:

**ImportError: .../anaconda3/envs/CMOR3.3.2/lib/python2.7/site-packages/cmor/../../../libcurl.so.4: undefined symbol: libssh2_exit**

**Comment by dnadeau4** [comment]
Do you have the latest libcurl version in your CMOR3.3.2 env? 
`...lib/libcurl.so.4.4.0`

**Comment by anfab** [comment]
In the lib folder of the 3.3.2 environment I can see libcurl.so.4 and
libcurl.so.4.5.0.



*********************************************************************************
Fabrizio Antonio

Advanced Scientific Computing (ASC) Division
Scientific Data Management (SDM) Research Group

CMCC Foundation
Euro-Mediterranean Center on Climate Change
Via Augusto Imperatore 16, 73100 Lecce, Italy

mobile: +39 329 5877826
email: fabrizio.antonio@cmcc.it
website: www.cmcc.it/people/antonio-fabrizio

*********************************************************************************

Il Mer 4 Apr 2018, 20:00 Denis Nadeau <notifications@github.com> ha scritto:

**Comment by dnadeau4** [comment]
Is you `LD_LIBRARY_PATH` variable set?  My guess is that your `python` is picking up the wrong `libcurl `version or `libssh`. 

You could try "ldd"  on your `_cmor.so` which should be around your `site-packages/cmor` directory.  That will give you a list of all the library needed by `_cmor.so`.  

Try `which python` to make sure that you are picking the `python` in your environment.

**Comment by anfab** [comment]
I think the problem was the **libssh2** library.
From the "ldd" output, I noted it linked to `/usr/lib64/libssh2.so.1`.
Adding `.../anaconda3/envs/CMOR3.3.2/lib/ `to **LD_LIBRARY_PATH** seems to solve the error.

Just a question. Comparing the ldd list for the 3.2.4 and 3.3.2 cmor versions, I noted that libssh2 is not required for the first version: is it a new requirement for the upgrated one?

Thanks

**Comment by dnadeau4** [comment]
It must be a new dependency of `libcurl`.  If you run `ldd` on `libcurl.so` from version `3.2.4` and `3.3.2` you should see the differences.    

`CMOR` comes with `CDMS2` which uses `libcurl` in order to access files from `OPeNDAP` sites.  `libssl2` is used to make a secure link with `https` or when you need authentication using certificate and keys.  

`CDMS2` can also use certificates to access CMIP6 or CMIP5 data directly from `ESGF` sites.  You can retrieve the key/certificate using `myproxyclient`.  

That is quite useful for you don't have to download the file to your local machine. 😄

**Comment by anfab** [comment]
Thank you so much for that very full answer.
