### ISSUE TITLE
"Alevhalf" dimension but "alternate hybrid sigma pressure" axis

### ISSUE THREAD

**Issue by wachsylon** [PCMDI/cmor#351]
Hi,
I try to convert variables requested on "alevhalf" dimension which requires [no bounds](http://clipc-services.ceda.ac.uk/dreq/u/dim:alevhalf.html). However, the model uses a "alternate hybrid sigma pressure" axis which [must have bounds](https://github.com/PCMDI/cmip6-cmor-tables/blob/2e2fb6058b495a7de94415007df3c73a2c51fbb4/Tables/CMIP6_coordinate.json#L241). If I try to register a z_axis without bounds with
```
                  cmf = cmor_axis(new_axis_id(axis_ids), (char *) "alternate_hybrid_sigma", (char *) "", zsize,
                              (void *) alev_val, 'd', NULL, 1, NULL);
                  cmf = cmor_zfactor(zfactor_id, lev_id, (char *) "p0", (char *) "Pa", 0, 0, 'd', (void *) p0, NULL);
                  cmf = cmor_zfactor(zfactor_id, lev_id, (char *) "b", (char *) "", 1, &lev_id_array[0], 'd',
                                 (void *) b_val, NULL);
                  cmf = cmor_zfactor(zfactor_id, lev_id, (char *) "ap", (char *) "Pa", 1, &lev_id_array[0], 'd',
                                 (void *) ap_val, NULL);
                  cmf = cmor_zfactor(zfactor_id, lev_id, (char *) "ps", (char *) "Pa", count_axis_ids(axis_ids) - 1,
                                 axis_ids, 'd', NULL, NULL);
```
I get an error. What do I have to do?
Best regards and thank you,
Fabi

**Comment by wachsylon** [comment]
[Phalf](https://github.com/PCMDI/cmip6-cmor-tables/blob/2e2fb6058b495a7de94415007df3c73a2c51fbb4/Tables/CMIP6_AERmon.json#L1727) would be such a variable for example.

**Comment by wachsylon** [comment]
In CMIP5 data I can see that the "alternate hybrid sigma pressure" axis is provided with bounds for those half levels. Is this the way to go in CMIP6 as well?

**Comment by taylor13** [comment]
No, there should be an option to write the half-levels as the coordinate values and not include any bounds.  In the data request some variables are a function of alevel, and others are a function of alevhalf.  I think we either need to add new entries to the CMOR table for all the model level coordinates or make CMOR smart enough to know that variables that are a function of alevhalf don't have bounds, but those that are a function of alevel do have bounds.  Will talk to @doutriaux1 and decide what to do.  Thanks for pointing out this bug.

**Comment by taylor13** [comment]
@wachsylon It would help us decide what to do here if you would check what happens if you supply artificial bounds for the half-level coordinates.  I know from a modeling perspective, we don't want bounds in this case, but we're exploring options for a work-around, and we want to make sure we understand the problem.

In particular, when you say (https://github.com/PCMDI/cmor/issues/351#issue-324428865) "I try to convert variables requested on "alevhalf" dimension which requires no bounds", how did you know it shouldn't need any bounds?  Was that indicated in the CMIP6 data request?  Or do you know that because of your understanding of models?

thanks for your help with this.

**Comment by wachsylon** [comment]
I just asked myself what bounds can actually be in the case of the alevhalf dimension. For me, these half-level are the actual bounds of the axis the model used. However, I searched in Dreq and found 

> bounds: no

[under this link](http://clipc-services.ceda.ac.uk/dreq/u/dim:alevhalf.html). When you say 

> we don't want bounds in this case

do you mean the axis must not have bounds? It could be hard in this case to find a work-around.

I am sorry that I cannot provide the exact error message but I know that 
```
cmf = cmor_axis(new_axis_id(axis_ids), (char *) "alternate_hybrid_sigma", (char *) "", zsize,
                              (void *) alev_val, 'd', NULL, 1, NULL);
``` 
did not work because axis `"alternate hybrid sigma"` has [attribute](https://github.com/PCMDI/cmip6-cmor-tables/blob/508ccbde87d8b55bd26eeecd43851061a20da514/Tables/CMIP6_coordinate.json#L241) 

> "must_have_bounds": "yes"

**Comment by doutriaux1** [comment]
@wachsylon I was talking about this with @taylor13 yesterday, he feels we might need to create new entries for half levels coordinate with `"must_have_bounds":"no"` 
@taylor13 is that the way you want to go?

**Comment by wachsylon** [comment]
The problem however is that all atmospheric axes can be provided for `alevhalf`, correct? So it could be better to teach CMOR to ignore this attribute `"must_have_bounds":"no"` when `alevhalf` is the dimension. This again is hard since function `cmor_axis` needs to be called before `cmor_variable`...

**Comment by wachsylon** [comment]
A suggestion: What about having a coordinate attribute that points to another coordinate? That reduces the repetition in the coordinate.json. In this case we could have sth like:
```
"alternate_hybrid_sigma_half": {
  <link_attribute>: "alternate_hybrid_sigma"
  "must_have_bounds" : "no"
}
"alternate_hybrid_sigma": {
...
```
All attribute specifications of "alternate_hybrid_sigma_half" overwrite the linked axis attribute specifications, the rest is taken from the linked axis. This could be also translated to single coordinates, e.g.:
```
"depth0m": {
  <link_attribute>: "depth"
  "valid_max": "100.0", 
  "valid_min": "0.0", 
  "value": "0."
}
"depth":{
...
```
I can see of course that his is a big change - but at least a try.

**Comment by doutriaux1** [comment]
@wachsylon it's a good suggestion, maybe a bit late in the game though, at this point considering the amount of time we can dedicate to CMOR it might not be implemented right away.

**Comment by taylor13** [comment]
@wachsylon:  @doutriaux1 and I considered the options and decided we'll make CMOR smarter by:

1) adding half-level versions of all the atmospheric parametric vertical coordinates (those with "zfactors"), and set for these must_have_bounds="no".  The table entry names will be the same as for the alevel version but with "half" appended (e.g., "standard_sigma" becomes "standard_sigma_half")
2) adding a new attribute to all parametric vertical coordinates.  In the coordinates.json file where these coordinates are defined, we'll specify "generic_level_name" set to "alevel", "alevhalf", or "olevel".  

The code will be modified so that the user will need to define a parametric vertical coordinate variable that has "generic_level_name" consistent with a variable's "dimensions" specification.  So, for example, if a variable has a dimension "alevhalf", the user will need to define one of the parametric variables for which generic_level_name = "alevhalf".

**Comment by taylor13** [comment]
The variables that should be identified as generic_level_name = "alevel" are:
alternate_hybrid_sigma
hybrid_height
natural_log_pressure
smooth_level
standard_hybrid_sigma
standard_sigma

For each of the above we need to add a half-level version with generic_level_name = "alevhalf".

The variables that should be identified as generic_level_name = "olevel" are: 
depth_coord
ocean_double_sigma
ocean_s
ocean_sigma
ocean_sigma_z
