### ISSUE TITLE
Decadals

### ISSUE THREAD

**Issue by wachsylon** [PCMDI/cmor#405]
Hi,
according to the CF-Conventions ([Example 7.10. Decadal averages for January](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html)), the time axis for a decadal variable is described with `climatology_bounds`. Therefore, all variables in table[ CMIP6_Odec.json](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_Odec.json) should rather have `"dimensions" : "time2"` and `"cell_methods" : "time: mean within years time: mean over years"`.

Am I correct? This is probably a DReq issue so that I post it there as well.
Best regards,
Fabi

**Comment by taylor13** [comment]
When the time period over which an average is computed is contiguous, it is not generally considered a climatology.  In this case, since the bounds of the time-period coincide with the beginning of one year and the end of another, it *could* be considered a 10-year annual mean climatology,  but it equally could be considered a ten-year mean.  This is unlike a climatological annual cycle (which might be represented by 12 monthly means, each representing an average over multiple years) or a climatological diurnal cycle (which might be represented by 24 hourly means, each representing an average over multiple days).  
Successive decadal means (over successive 120 month intervals) can be represented in a simpler way with a normal time dimension and with cell_methods = "time: mean" and bounds spanning 10-year intervals.  So, I think the current DReq is correct as is.

**Comment by wachsylon** [comment]
Thanks for the quick response. My mistake, sorry. One additional question:
Do you know if there is a specific interval requested for the decadals? For example, 1961-1970 or 1960-1669?

**Comment by durack1** [comment]
@wachsylon thanks for raising these questions, I agree there should be some description about this in the DREQ. I'll pull @martinjuckes into this discussion as an additional note with temporal bound guidance is likely required upstream in the [`Odec`](http://clipc-services.ceda.ac.uk/dreq/u/MIPtable::Odec.html) table

**Comment by taylor13** [comment]
I vaguely recall that there has been some discussion elsewhere of what specific intervals should be saved for decadal means.  Perhaps @senesis or @martinjuckes can point us to that discussion?

**Comment by senesis** [comment]
No, sorry

**Comment by taylor13** [comment]
Thanks very much @matthew-mizielinski for reminding us of that.  I agree, that since in control runs absolute time has no meaning (one shouldn't associate any historical date with the control run "date"), there should be no special preference for defining specific years to the beginning and ending of each 10-year period.  Any "guidance" we generate should say that "the reason for keeping these fields is almost entirely to monitor the approach to (quasi) equilibrium in the control runs, and since the years simulated in the control runs do not correspond to historical years, the year that each decade begins is arbitrary (although their spacing must be 10 years)."

**Comment by martinjuckes** [comment]
Hi Karl, I agree, but it is important, however, to have some consistency within the data generated by each model (this will be simple if all the data is published in one go, but if some variables are dealt with a year later by different people there is a danger that a different arbitrary number could be selected).

It might be useful if the 10-year periods used ended at the point where the piControl run starts .. should we recommend that? Presumably the last 10 year period should at least include the start of the piControl run?

**Comment by taylor13** [comment]
@martinjuckes regarding your first paragraph above, I think you are saying that the same decadal intervals should be used for all variables requested.  If so, I agree that would be best.

Regarding paragraph 2, I think it should be required that all decades be included, at least up to and including the decade when the first historical "realization" is initiated.  It wouldn't hurt to include *all* decades in the control.  I think it unlikely that groups will know exactly at what points their historical runs will be initiated, and again I can't think of any reason to recommend that they be initiated at the end/beginning of one of the sampling decades.

**Comment by matthew-mizielinski** [comment]
@senesis, this is an important point that warrants some consideration for CMIP7, i.e. should we allow this form of time slicing?
Groups who retain all model data that might be needed and then process variables that are requested may be able to cope with this, but the more efficient data production approach used by CNRM & IPSL will be constrained if these requestItems are retained.

The branching point for our HadGEM3/UKESM1 historical simulations was chosen based on the state of various indices (AMO & PDO phases) to give some spread, which of course we couldn't do if we had to decide on the branching dates before the piControl was started.

**Comment by senesis** [comment]
@matthew-mizielinski : CNRM scientists did find scientifically sensible (and fair) to make a random choice of branching point, rather than to force a spread. I agree that the CMIP protocol shouldn't be silent on that point

**Comment by taylor13** [comment]
@senesis @matthew-mizielinski Do I understand correctly that 
1) UKMO spawned historical runs from the piControl at points chosen to capture a range of phases of certain multi-year unforced oscillations in the climate system, whereas
2) CNRM randomly selected branch points?
If CMIP should not be silent on this point, what should CMIP recommend?

**Comment by senesis** [comment]
You do understand correctly. But this is not the right place to discuss that,  is it ? What about the CMIP Panel ?

**Comment by taylor13** [comment]
Thanks, Stéphane.  It is indeed a science question, not a CMOR question, but I won't close this yet in case @matthew-mizielinski  has something he wants to add.

**Comment by matthew-mizielinski** [comment]
Nothing more from me.

**Comment by wachsylon** [comment]
I would like to notice an additional thought: The file name convention for decadal variables leads to misleading file names, especially if we have files which cover one or two decades. Assume there is a variable calculated for 4 decades in two files. We would have for example:
*1855-1865.nc
*1875-1885.nc
If I found a file *1855-1865.nc I would assume that it covers the decade 1855-1865.

**Comment by taylor13** [comment]
I agree this was a mistake in our specifications for CMIP6.  In the model output requirements document (https://goo.gl/neswPr) it states: 
```
For time coordinates with defined bounds (e.g., for time-means), the coordinate values must be
 defined as the mid-points of the intervals over which each average is computed. 
```
And in Table 2 of the CMIP6 specs document  (https://goo.gl/v1drZl)  it says to generate a
```
Label with the years recorded in the  first and last coordinate values.
```
In the case of the first file you describe above, the first and last coordinate values are 1855 and 1865 (found at the center of each decadal mean), so the correct (but misleading) label is 1855-1865.  I think it is too late to change this for CMIP6 because I think we want all files to follow the same rules.

**Comment by durack1** [comment]
Issue migrated to https://github.com/cmip6dr/cmip7_forward_look/issues/41
