### ISSUE TITLE
Question concerning grid_label

### ISSUE THREAD

**Issue by durack1** [PCMDI/cmor#437]
```
On 11/20/18, 4:25 AM, "Ingo Bethke" wrote:

    Hi
    
    Two questions concerning use of grid_label: 
    
    1. Should different values for grid_label be used only to distinguish between
 different horizontal grids or also to distinguish between native and interpolated
 vertical levels? 
    
    The ocean component of NorESM has a vertical density coordinate and we
 can provide both output on native density coordinate and interpolated to
 standard z-levels. If the CMOR3 CMIP6 standard does not support it out of
 the box then we will opt with only interpolated ouput on standard z-levels.  
     
    2. The request to provide (ocean + sea ice) output on native horizontal grid
 as well as interpolated regular grid, is that a soft request or a hard request? 
    
    Storage space is a real concern for our group, apart from the extra effort of
 producing the interpolated cmor-ized output. Personally I prefered if the 
major data centres that are going to replicate the CMIP6 model output from 
various ESM groups also took care of interpolating this output to a common 
grid. As it stands now, each model group has to develop and implement their 
own interpolation capability in their post-processing setup, which seems like 
a duplication of effort.  
    
    Kind regards 
    Ingo
    NORCE Norwegian Research Centre AS
    norceresearch.no
```
@IngoBethke @taylor13

**Comment by doutriaux1** [comment]
@durack1 concerning -1- as far as I remember CMOR's grid are horizontal only. 
Concerning -2- let's ping @taylor13

**Comment by taylor13** [comment]
I wrote Ingo checking whether the questions still stood:

```
It was just brought to my attention that your questions had not yet been 
answered; very sorry about that.  I'm sure you've made your decisions on 
what to do, but if not, please let me know I will answer right away.

You might be interested in reviewing the plan for modeling groups to 
provide regridding weights to several target grids, so that users can 
regrid the data they download.  This is particularly important when 
conservation is essential and when model output is archived on 
non-regular grids.  Here is the location of the document describing the 
weights file structure and application of the weights to regrid data: 
https://docs.google.com/document/d/1BfVVsKAk9MAsOYstwFSWI2ZBt5mrO_Nmcu7rLGDuL08/edit
```

In reply Ingo wrote (in part):
```
Thanks for your reply and information on the regridding weights. Your feedback is much 
appreciated ...   The google-doc answers already answers my question 2. So we are not 
going to provide output that is readily interpolated to a regular horizontal grid. Instead 
we will provide interpolation weights - generated with the ESMF weight generator - that 
conform to the specifications of the google-doc. To use such weights to interpolate 3d 
ocean data the user will also have to consider bathymetry information but I’m sure you 
have given this some thought or maybe decided that there is no demand for interpolated 
3d fields. 

Concerning question 1: 

Do you think it is possible for us to provide 3d ocean data on both native vertical model 
coordinate (which approximates potential density but differs from it in the upper layers) 
and interpolated to z-levels? If yes, how should we choose the grid_label for the two 
sets?

If not, I assume the preference of most MIPs is interpolated to z-levels. OMIP may be 
an exception since it targets mainly ocean model developers who generally prefer the 
highest accuracy possible when analysing the output. Maybe best we can contact to 
the OMIP leaders for their advise. 
```
i will respond here shortly.

**Comment by taylor13** [comment]
I hadn't considered whether a grid label of "gn" should be used when data are reported on the native horizontal grid, but have been interpolated vertically.  Thinking about it now, and realizing that the vast majority of atmospheric 3-d data is interpolated in the vertical to standard pressure levels, I think the rule should be:

"a variable reported on the native horizontal grid should be labeled "gn" with this exception:  if the variable is reported on levels that are not native to the model *and* when there exists another dataset where that same variable has been reported on model levels, the variable should be assigned the label gri (where i is replaced by an integer, e.g., gr1, gr2, etc.) to distinguish it from the one stored on native levels on the native horizontal grid."

If you want to report a single variable on two grids, both native horizontal grids, then the output reported on the models native density coordinate levels would be labeled "gn"; the same variable reported on z-levels could be labeled "r1".

If you want to report a single variable on two grids, one of which is the native *horizontal* grid and the other has been regridded horizontally, these would be labeled "gn" and "gr1", respectively, regardless of any vertical interpolation.

If you want to regrid a single variable to a single horizontal destination grid and report one on the native density levels and the other on z-levels, you should decide which you want to deem "primary" and label it "gr"; the other one could then be labeled "gr1".

By the way, if you regrid some variables in one way, and others in another, "gn" could take on different meanings, depending on the variable.  For example, suppose both variables are reported on the same native horizontal grid, but one has been interpolated in the vertical, while the other hasn't.  Both variables would be assigned "gn", but clearly that does not imply that they have the same vertical coordinate; it only implies that they are both on the native horizontal grid.

 The only thing that is absolutely essential in all this is that the grid labels must lead to uniquely named files.  The secondary thing is that the grid_label should give users an idea about what grid a modeling group thinks best reflects their simulation.  That should be "gn" or "gr".

**Comment by wachsylon** [comment]
Since the MIPs are decentrally organized and everything could happen: What if someone want to report a variable on model level after I reported the same variable on interpolated coordinates?

**Comment by taylor13** [comment]
Good point!  The only essential thing is that they choose a different grid label from yours.  

If your data were on the native horizontal grid, you would have chosen "gn".  "someone" will have no choice but to use gr1, gr2, or the like for their files. 

If your data were regridded away from the native horizontal grid, you would have likely chosen "gr", indicating it was your choice for "primary grid".  If "someone's" data was on the native grid, it would be natural to use the label "gn", but this breaks the rule that modeling groups can use either "gn" or "gr" to label their primary output, but not both.  This means "someone" would have to use "gr1", "gr2", etc., since you already published with "gr".  

The reason for the rule "only 1 primary grid", which should be labeled either "gn" or "gr" depending on the horizontal grid, is that someone searching for data may want to download data from every model, but only on 1 of their grids.  If, under the "grid" search facet, the user selects "gn" and "gr", then 1 and only 1 output dataset per model will be found (and those datasets will be on the model's primary grid, as designated by the modeling group).  

This is obviously rather complicated, and we hope for CMIP7 to find a more straightforward way for users to select only one gridded output dataset per model.

comments welcome.

**Comment by taylor13** [comment]
@wachsylon @IngoBethke  I am closing this issue.  Please reopen if their are unresolved questions.

**Comment by wachsylon** [comment]
I think your suggestion will be very hard to implement since you write in CMIP-6.2:

> The grid labels (“gr1”, “gr2”, etc.)  must be defined consistently for all variables reported from a single model on the same secondary grid.  

There is variable `ch4` in Amon, AERmonz, AERmon, E3hrPt requested on `alevel`, `plev19` and `plev39`. So if I plan to report all, I have to report ALL variables given on `plev19` axes with a specific `grid_label`, e.g. `gr1` ? That means I have to check all plev axes whether they are requested for a variable which is also requested on model level. Also, I have to check the grids... Too much work if you ask me :)

**Comment by taylor13** [comment]
I should have indicated that the rule stated at the top of https://github.com/PCMDI/cmor/issues/437#issuecomment-461222809 only comes into play for certain ocean data, where users can decide whether to report a variable appearing in a *single* cmor table on both model levels *and* on z-levels.  In the atmosphere, (e.g., in the case of ch4), if a variable is reported on the same horizontal grid, it should invariably have the same grid label, independent of the vertical coordinate.  There will be no conflicts in file names because variables from different tables always are distinguishable using the table name.  For CH4, for example, Amon and AERmonz request CH4 on plev19 and plev39, respectively, but they should have the same grid label (if they are reported on the same horizontal grid).  Similarly, CH4 from E3hrPt and AerMON would also have that same grid label even if though they are reported on model levels.  

I'm not sure I followed your use case, but with this clarification of the rule, would it still be a lot of work?  (You can say "yes".)

**Comment by wachsylon** [comment]
> I'm not sure I followed your use case, but with this clarification of the rule, would it still be a lot of work? (You can say "yes".)

I guess for the ocean modelers..
