### ISSUE TITLE
cmor.write segfault related to timesteps

### ISSUE THREAD

**Issue by chloemackallah** [PCMDI/cmor#440]
In recent testing of CMOR with the ACCESS model, we found an issue when attempting to use cmor.write, but with an incorrect value assigned to argument 'ntimes_passed'.
In this scenario, when the value of 'ntimes_passed' was inconsistent with the actual number of timesteps contained within the data that is passed to cmor.write, the result is a segmentation fault. This made it difficult to track the source of the error.
We would suggest an instructional error message be output if this occurs rather than a segmentation fault. Additionally, perhaps it would be possible to implement a check that the number of time values is consistent and initialise the dimension length accordingly.

**Comment by mauzey1** [comment]
@doutriaux1 I am currently trying to make a way to check if the number of times passed exceed the length of the time axis.

https://github.com/PCMDI/cmor/blob/7c7e48a1b3c003c7eb712838929fde3ca62f2f8d/Src/cmor.c#L4392-L4412

I am not sure how well it handles cases where it is writing data to a zfactor.  I tried putting this check below the call to `cmor_set_refvar` since it sets the ntimes_written attribute of the zfactor with ntimes_written of the associated variable minus ntimes_passed.

https://github.com/PCMDI/cmor/blob/7c7e48a1b3c003c7eb712838929fde3ca62f2f8d/Src/cmor.c#L2441-L2442

It currently passes all of the current tests in the test suite.  I also made a test to see if it gets the error for passing more times to cmor_write than the length of the time axis.
https://github.com/PCMDI/cmor/blob/440_cmor_write_segfault_related_to_timesteps/Test/test_python_CMIP6_CV_times_written_exceeded.py

Are there any other tests I could throw at it?

**Comment by mauzey1** [comment]
@chloemackallah I would like to revisit this issue by figuring out how to replicate the error you were experiencing.  Could you submit some sample code that causes this error?

> In this scenario, when the value of 'ntimes_passed' was inconsistent with the actual number of timesteps contained within the data that is passed to cmor.write, the result is a segmentation fault.

I wonder if this was already solved in https://github.com/PCMDI/cmor/issues/485, at least for Python code.

**Comment by chloemackallah** [comment]
@mauzey1 It does look like this was solved in #485 and #500, as that catches the seg fault.

**Comment by mauzey1** [comment]
@chloemackallah Do you think this issue can be closed now?

**Comment by mauzey1** [comment]
I will close this for now.
