### ISSUE TITLE
Keeping track of the CMOR version

### ISSUE THREAD

**Issue by ehogan** [PCMDI/cmor#49]
I was having an issue with CMOR similar to that described in issue #6. To see if the fix from issue #6 resolved my issue, I downloaded v2.9.2 from https://github.com/PCMDI/cmor/releases, since the issue was added to the v2.9.2 milestone (https://github.com/PCMDI/cmor/issues/6#event-314001946). However, I discovered the fix wasn't included in the v2.9.2 release and that the CMOR version in this release was still v2.9.1.

Looking at the fix itself (https://github.com/PCMDI/cmor/commit/a100f8f11de8bb957d709a1bb18b59d1a0032417) I realised that it had only been tagged `uvcdat-2.4.0` (why not v2.9.3?), so I downloaded this version only to discover that the CMOR version was still v2.9.1.

Would it be possible to ensure that the version number of CMOR is correctly updated for every release? This is important for reproducibility purposes (since the CMOR version is written to the headers of the output netCDF files), especially for CMIP6. In addition, would it be possible to ensure that issues are added to the correct milestone? This would be useful when determining which releases contain specific fixes.

I heard that Karl @taylor13 may be interested in hearing about this issue.

[The fix from issue #6 did resolve my issue, which I was very happy about] ;)

**Comment by doutriaux1** [comment]
hi @ehogan the `uvcdat-2.4.0` was simply a tag for [UV-CDAT](http://github.com/UV-CDAT/uvcdat) since CMOR is distributed as part of UVCDAT we wanted to make sure that user building uvcdat 2.4.0 would always get this version of cmor. @nadeau4 and I will take a look at your issue and make sure it is solved in the upcoming 3.0 release. Thanks!

**Comment by ehogan** [comment]
That sounds great @doutriaux1, thank you very much! :)

**Comment by dnadeau4** [comment]
ehogan,

I am working on CMOR 3.0 and I have an alpha release in branch cmor3 due today.  You will need to install the json tables found in https://github.com/PCMDI/xml-cmor3-database/tree/master/src and there is a new library called libjson-c that needs to be installed and passed to the configure.  I should have more documentation by the end of the day.

Denis

**Comment by doutriaux1** [comment]
@dnadeau4 let's make sure that her bug is fixed in this release, thanks.

**Comment by durack1** [comment]
@doutriaux1 @dnadeau4 I think the point raised by @ehogan is a good one.

Why not just tag the CMOR version for the UV-CDAT release with the current CMOR release - so `2.9.3` or `2.9.2` rather than create an arbitrary duplicate tag/release point. The intention is to lock versions, so whether this is a tagpoint named `uvdat-2.4.0` or '2.9.2/3` it achieves the same aim

**Comment by doutriaux1** [comment]
Yes especially since for CMOR master is always the latest stable version. That makes sense.

**Comment by durack1** [comment]
@doutriaux1 well `master` keeps moving, `2.9.3` (or similar) shouldn't..

**Comment by doutriaux1** [comment]
@durack1 yes but I was saying that we don't need a uvcdat specific tag point since uvcdat uses master and master is always at some tag point.

**Comment by dnadeau4** [comment]
master has now been moved to CMOR 3.1.0
