### ISSUE TITLE
CMOR3.4.0 appears to only be available on nightly channel, not main

### ISSUE THREAD

**Issue by durack1** [PCMDI/cmor#507]
I just took a look at https://anaconda.org/PCMDI/cmor/files and it seems that CMOR3.3.3 is the latest
![Screenshot_2019-07-02 Cmor Anaconda Cloud](https://user-images.githubusercontent.com/3229632/60541589-c55a5500-9cc6-11e9-8508-28254048e075.png)
I was under the impression CMOR3.4.0 was the latest official release?

@mauzey1 is there something awry here?

**Comment by durack1** [comment]
@mauzey1 I have just noted that CMOR3.4.0 is available through conda-forge https://anaconda.org/conda-forge/cmor/ - not sure if the PCMDI repo should point this out?

**Comment by mauzey1** [comment]
@durack1 Yes, we are currently storing the latest stable CMOR on conda-forge.  I think 3.3.3.npy1.14 is being displayed as the current version on PCMDI's repo because it's last one with the `main` tag.

CMOR's [Anaconda installation instruction](https://cmor.llnl.gov/mydoc_cmor3_conda/#installing) use conda-forge to get the stable release of CMOR.

@doutriaux1 Should we include stable releases of CMOR in the PCMDI Anaconda repo along side nightly?

**Comment by durack1** [comment]
@mauzey1 @doutriaux1 as a user who has followed a previous (not up-to-date) recipe, and who didn't read the updated documentation this was a time waster for me. I think we should do what we can to make it clear to users that conda-forge is the primary source of conda releases, and this has changed recently from the PCMDI channels

**Comment by durack1** [comment]
This is no longer relevant, closing
