### ISSUE TITLE
A question about the variable_id global attribute

### ISSUE THREAD

**Issue by ehogan** [PCMDI/cmor#518]
Would it be worth setting the value of the `variable_id` global attribute to the `variable_entry` rather than the `out_name` to help identify the corresponding entry for the variable in the MIP tables?

**Comment by taylor13** [comment]
variable_id is supposed to be used to generate the file name and directory structure, so I don't think we should change it.  It might also mess up the ESGF search, because outname is used as a search facet and is obtained from variable_id.  
 You are certainly free to add a variable_entry global attribute to your files, and we might consider implementing that more generally.  Does this make sense?

**Comment by ehogan** [comment]
Thanks @taylor13 :) I wasn't sure whether `variable_id` in the output netCDF file was used by ESGF. We added our own global attribute, but we thought it was worth mentioning in case other CMOR users might find it useful? :)

**Comment by taylor13** [comment]
@ehogan I will close this, but if there is further steps to take, please reopen. Thanks.
