### ISSUE TITLE
invalid time units "day as %Y%m%d.%f" 

### ISSUE THREAD

**Issue by chrisdane** [PCMDI/cmor#554]
Hi
cdo cmor gives the error
```
! Error: Your  "parent_time_units" set to "day as %Y%m%d.%f" is invalid. 
! Please refer to the CMIP6 documentations.
```
The time of my model output indeed is 
```
        double time(time) ;
                time:standard_name = "time" ;
                time:units = "day as %Y%m%d.%f" ;
                time:calendar = "proleptic_gregorian" ;
                time:axis = "T" ;
```
What can I do? 
Thanks, Chris

**Comment by wachsylon** [comment]
We discuss this Problem via pm.
Best,
Fabi

**Comment by durack1** [comment]
@wachsylon this looks like a `CDO-cmor` problem, so can we close this issue in this repo? If you have an equivalent new issue in the `CDO-cmor` repo, please tag this issue here

**Comment by chrisdane** [comment]
Yes it was a typical read-the-manual-problem - so my fault. Thank you @wachsylon!

However, I find it extremely difficult to keep track of all necessary information to successfully cmorize my model data. For CMIP7, one (1) homepage should be used, not ~10 (?) and especially not any ominous google documents such as https://goo.gl/neswPr. I consider links like these as spam (and everyone should do so).

**Comment by durack1** [comment]
@chrisdane I’m curious that you’ve had to hit 10 separate sites to write data, didn’t https://cmor.llnl.gov plus https://pcmdi.llnl.gov/CMIP6/Guide/modelers.html suffice?

Can you outline more specifically what sites you’ve had to hit?

**Comment by chrisdane** [comment]
1. info page (with a lot of follow-up links):  https://earthsystemcog.org/projects/wip/CMIP6DataRequest
2. info page 2 (with a lot og follow-up links): https://pcmdi.llnl.gov/CMIP6/Guide/modelers.html
3. DR: http://proj.badc.rl.ac.uk/svn/exarch/CMIP6dreq/tags
4. another DR page: http://clipc-services.ceda.ac.uk/dreq
5. another DR page specifically for one of my used models: https://c6dreq.dkrz.de
6. cmor tables: https://github.com/PCMDI/cmip6-cmor-tables
7. CVs: https://github.com/WCRP-CMIP/CMIP6_CVs
8. cmor: https://cmor.llnl.gov 
9. google document: https://goo.gl/neswPr

... definitely I am not aware of other pages, especially google documents. 

My point is that in my opinion a clear how-to-cmorize-your-data-for-cmip6-if-you-want-to-participate-in-mip1,mip2,mipN-and-expA-expB-expM does not exist. For me, the whole cmorizing is very cumbersome and time consuming, although in the end its just a bunch of cdo commands.

**Comment by durack1** [comment]
@chrisdane thanks for the feedback. With the expansion of CMIP6 to include 299 projects, the workload has increased for modellers in ascertaining what data, and preparing that data for publication.

The pages that you link to above are not all necessary to use CMOR. I note that as you are using the CDO-CMOR package, support is not provided by PCMDI.

In order to generate output using CMOR3 for CMIP6, all you should need to do is install the CMOR3 package (following guidance at https://cmor.llnl.gov) and then clone the cmip6-cmor-tables for use by CMOR3, and then ascertain the variables you want to write with these defined at http://clipc-services.ceda.ac.uk/dreq/ or the python instance for a more automated, script-able path forward. Publication to ESGF happens after you have the files (and directories) generated.
