### ISSUE TITLE
bug in parsing coordinate variables in 3.6.0

### ISSUE THREAD

**Issue by YanchunHe** [PCMDI/cmor#617]
Hi,

CMOR 3.6.0 updates 'Tables/CMIP6_formula_terms.json'. However, some of the code in cmor 3.6.0 are not updated correspondingly.

For example, it will crash when processing variables defining on `alevhalf`, such as `phalf` in Amon.
```
C Traceback:
! In function: cmor_variable
! called from: cmor_zfactor
!

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: Could not find a matching variable for name: 'b_half_bnds'
!
!!!!!!!!!!!!!!!!!!!!!!!!!
```
Commeting out line 603 of `Src/cmor_variable.c` should fix this.
```fortran
strncat(msg, "_bnds", CMOR_MAX_STRING - strlen(msg));
```

However, this fix will introduce error for other variables defining on `alevel`, e.g., `pfull`
```log
^[[2;31;47mC Traceback:
! In function: cmor_define_zfactors_vars
! ^[[0m

^[[1;31;47m!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: could not find the zfactor variable: a_bnds.
! Please define zfactor before defining the
! variable cli (table Amon).
!
! Also zfactor dimensions must match variable's dimensions.
!
!
!!!!!!!!!!!!!!!!!!!!!!!!!^
```

Could someone fix this?

Many thanks in advance!

Yanchun

**Comment by taylor13** [comment]
For all model formulations we are aware of variables defined on half levels have no bounds.  [That is, there is no use for bounds on the half-levels, because the half-levels are the bounds for the cells themselves.  The half-levels are not cell coordinates but bounds on cells.]   

The output specifications given [here](https://docs.google.com/document/d/1os9rZ11U0ajY7F8FWtgU4B49KcB59aFlBVGfLC4ahXs/edit) say that variables reported on half levels do not need bounds.  In fact the CMIP6_coordinate.json file indicates that for all the "alevhalf" variables,
```
  "must_have_bounds": "no", 
  "z_bounds_factors": "", 
```
Thus, CMOR will not find a match for ``b_half_bnds`` and will error exit.  The file can be written successfully by omitting definition of bounds for the vertical coordinate of variables written on half levels.

**Comment by YanchunHe** [comment]
Thanks a lot for the comment! @taylor13 

I will try to omit defining the bounds in 'cmor_axis'

will update here later.

**Comment by YanchunHe** [comment]
This is fixed by omitting `cell_bounds` in `cmor_axis()` and `zfactor_bounds` in `cmor_zfactor()`.

I close this issue.

Thanks again for the help @taylor13 !
