### ISSUE TITLE
3.1 tagging

### ISSUE THREAD

**Issue by durack1** [PCMDI/cmor#62]
- [x] Update `master` branch with `cmor3` branch
- [x] Review all issue lists and close all redundant issues (move unresolved issues to next milestone)
- [x] Validate version info is correctly written (CMOR version should be `3.1.0`)
- [x] Validate data_specs_version written (01.beta.29)
- [x] Update [website](https://cmor.llnl.gov) so correct tag points (`3.1.0`) are noted for build notes
- [x] Prepare and publish release notes to [website](https://cmor.llnl.gov)
- [x] Create PDF from website.
- [x] Update `README.md` with updated `Stable version` info (should be `3.1.0`)
- [x] Set `3.1.0` tag point for PCMDI/cmor repo
- [x] Obtain Zenodo DOI
- [x] Finalize `README.md` with updated `Zenodo DOI` info
- [x] Move `3.1.0` tag point to new commit
- [x] After `3.1.0` tag point set, reset all `master` checkout tag points to point back to `cmor-master` tags.
- [x] Increment `cmor-master` to `3.1.1` (odd minor [major.minor.patch] number indicating development version)
- [x] Email mailing lists: `cmor@lists.llnl.gov, wgcm_wip@wcrp-climate.org, CDNOT@jiscmail.ac.uk, CMIP6-DATAREQUEST@JISCMAIL.AC.UK` including the text: `Please pass on this email to anyone you know who plans to prepare CMIP6 model output for the archive.`

**Comment by durack1** [comment]
@doutriaux1 pinging you here - I think @dnadeau4 needs some guidance about releasing `CMOR3`

**Comment by ehogan** [comment]
Would it be possible to add something about checking the milestones attached to issues to this list? In #49, I asked whether it would be possible to ensure that issues are added to the correct milestone, so that it was possible to determine which releases contain specific fixes. For example, there are [14 open issues](https://github.com/PCMDI/cmor/milestones/2.9.3) that currently belong to the 2.9.3 milestone, but since CMOR 2.9.3 has already been released, the fixes for those issues won't be part of the 2.9.3 release, so they shouldn't belong to the 2.9.3 milestone.

**Comment by doutriaux1** [comment]
thanks @ehogan I will go over these today with @dnadeau4

**Comment by durack1** [comment]
@ehogan good suggestion, it would be great to provide more comprehensive release notes, similar to what has been done with UV-CDAT recently, so:
https://github.com/UV-CDAT/uvcdat/releases/tag/v2.4.1
And specifically the link off this page to:
http://uvcdat.llnl.gov/changelog.html
