### ISSUE TITLE
enhancement for forecast data

### ISSUE THREAD

**Issue by taylor13** [PCMDI/cmor#623]
The decadal prediction community have proposed an extension of CMIP6 standards to accommodate additional metadata when forecasts are stored by CMOR.  Their proposal can be found at https://docs.google.com/document/d/1T-Xlkc07kzDbtyFp-JJiRQYmHO-OzFOgXjCvFGW5M7Y/edit .  

From a brief look at that document, it appears that it will be a non-trivial enhancement that might include:

1. Currently CMOR attaches a "coordinates" attribute to a variable for the following cases:
- scalar coordinates (e.g. variable tas has a scalar coordinate "height" where the height of the surface air temperature is stored)
- coordinates when text string labels are needed (e.g., for variables that are a function of some index, like the index used to distinguish between different ocean basins.  In this case the ocean basin name is stored in an auxiliary coordinate associated with the variable through the "coordinates" attribute.
- latitude and longitude values for grids other than cartesian latitude x longitude grids.

(See https://goo.gl/neswPr for further description of the CMIP6 requirements.)
For forecast data the "coordinates" attribute should include "reftime" and "leadtime" in its list.  The "reftime" is a scalar coordinate and can probably be treated by CMOR just like the other scalar coordinates except it probably should not have a default value specified in the CMOR table.  Also, CMOR may be currently limited to handling a single scalar coordinate for a given variable (not sure about this), so this might be an extension. 

Storing the "leadtime" will likely require more work.  This auxiliary coordinate variable must be the same size (length) as "time" and contains the time elapsed since the start of the forecast measured in days.  It is equivalent to "time" except for the reference time is specified in the time coordinate's units attribute, whereas the reference time for "leadtime" is stored in "reftime".  These two reference times will generally be different, so the "leadtime" will be offset from "time" by a constant amount.  CMOR could generate the "leadtime" values, given the "time" coordinate values, by simply subtracting from "time" the difference between "reftime" and the reference time stored in the units attribute of "time".  (Given this close and known relationship between leadtime and time, I wonder why "leadtime" is needed; wouldn't "reftime" be sufficient?)  

2. The format for "sub_experiment" has been extended to include the "day" as well as year and month when the experiment was initiated.  This seems like a minor change that should be easy to accommodate.  

3. There are additional global attributes called for that include free text supplied by the user.  I think CMOR can already handle these.

I'll try to get Paco to look this over and see if I've covered the requirements.  Also, perhaps he can explain the rationale for including "leadtime".

**Comment by martinjuckes** [comment]
Hello @taylor13 : thanks for raising this and mapping the requirements accurately into the CMOR framework. This looks good. It may be worth adding that the "reftime" coordinate should have `standard_name=forecast_reference_time` and "leadtime" should have "standard_name=forecast_period". 

Can we make it a requirement that "reftime" has the same `units` string as the time coordinate, and also that the units of the "leadtime" should be the same apart from the absence of the time datum (i.e. there is no "since ..." in `leadtime.units`)?

I think "reftime" also needs a `calendar`, which should match the time coordinate.

The requirement for "leadtime" comes, I believe, from the need to work with tools which can aggregate data across multiple files based on coordinates that are explicitly represented, as "leadtime" will be, but which are not currently able to work with a "leadtime" which is defined implicitly.  It occurs to be that this redundancy is avoided in vertical coordinates by using `formula_terms` rather than explicitly recording coordinates which can be easily computed. We don't currently have that option for "leadtime".

**Comment by durack1** [comment]
It will be useful to engage @matthew-mizielinski @mauzey1 and @piotrflorek on this issue

**Comment by matthew-mizielinski** [comment]
Hi All,

After a little thought I think I understand this as a step towards datasets containing a single variable for an ensemble of initialised simulations with different start dates.

If we consider the case where we have a decadal forecasting ensemble with members started every year from 2000 to 2005 each running for 10 years then we could imagine a single file with an ensemble dimension to cover the a set period, say 2005-2010, at which point the resulting files would look something like (ignoring bounds variables and global attributes)

```
netcdf tas_Amon_.... {
dimensions:
	time = UNLIMITED ; // (60 currently)
	lat = X ;
	lon = Y ;
	bnds = 2 ;
	realization = 6 ;
variables:
	double time(time) ;
		time:calendar = "gregorian" ;
		time:standard_name = "time" ;
		time:units = "days since 1850-01-01" ;
		...
	double leadtime(time, realization);
		leadtime:standard_name = "forecast_period" ;
		leadtime:calendar = "gregorian" ;
		leadtime:units = "days since forecast_reference_time" ;
		...
	double reftime(realization);
		reftime:standard_name = "forecast_reference_time" ;
		reftime:calendar = "gregorian" ;
		reftime:units = "days since 1850-01-01" ;
		...
	int realization(realization) ;
	        realization:standard_name = "realization" ;
		realization:units = 1 ;
		...
	double height ;
	        ...
	double lon(lon);
	        ...
	double lat(lat);
	        ...
	float tas(time, lat, lon, realization);
	        tas:standard_name = "air_temperature" ;
		tas:units = "K"  ;
		tas:coordinates = "height reftime leadtime" ;
		...
```

In this case the reftime would contain the equivalent of `[2000-01-01, 2001-01-01, ..., 2005-01-01]` and the first time record of `leadtime` would be something like `[5*365, 4*365, 3*365, 2*365, 365, 0]` (ignoring leap days).  The leadtime variable is a simple function of `reftime` and `time`, as @martinjuckes alludes to when referring to the `formula_terms` used in vertical coordinates such as hybrid height, but I believe it is crucial to work that is more closely aligned with initialised forecasts than with climate.

Adding `reftime` and `leadtime` to the `tas:coordinates` attribute then makes clear that these are extra information, rather than being associated with a particular axis of the data variable.

It would also be possible to construct examples where there is a significant amount of missing data, e.g. if the file in question covered 2000-2005 with the same start dates for the realizations then around half of the data variable would be missing data and the corresponding `leadtime` would be negative (or should this be masked?).  Some thought on appropriate chunking may be needed to ensure reasonable performance.

If I've interpreted this correctly then the document that @taylor13 has linked to above is not recommending the above structure, but a step towards it, with only a single ensemble member per file and as a result the `realization` dimension gets squeezed out.

I think an argument could be made for retaining the realization as a dimension if only to allow CMOR to support the general case.

**Comment by durack1** [comment]
Possibly a very dumb suggestion, but here goes..

If the `leadtime` and `reftime` are functions of the `time` variable, why not just make these

**Comment by martinjuckes** [comment]
@matthew-mizielinski : regarding your last two paragraphs: yes, this is a recommendation for including additional CF metadata about `forecast_reference_time` and `forecast_period` without departing from the established CMIP practice of having data from a single simulation in each data file. The decadal forecast community who are asking for this are used to working with data from multiple start-times in a single file, but they will be able to adapt easily to the proposed approach if the information requested above is added (e.g. it will be possible to combine data with different start times into a single file using a simple CDO command .. Pierre-Antoine Bretoniere, the 2nd author has tested this). Leon Hermanson from UKMO has also been involved in the discussions (there is a list of contributors in section 4).

**Comment by taylor13** [comment]
In that case, I think we shouldn't try to extend CMOR to handle multiple simulations (start times) in a single file; that would require major changes.

**Comment by matthew-mizielinski** [comment]
Thanks @martinjuckes, I've had a chat with Leon about this (this was the initial motivation for us getting more involved in CMOR). Given that there is a tool for ensemble combination and @taylor13's suggestion that major changes would be needed we'll start with the single ensemble member case.

@taylor12, @durack1, If you are happy with the following I'll leave @piotr-florek-mo and @mauzey1 to start discussing API details. We need to add the following functionality;
 * ability to add an "auxilliary" `leadtime` axis or define an axis pair instead of a single `time` dimension
 * ability to add scalar dimensions for the `realization` and `reftime` variables
 * appropriate handling of `coordinates` attribute

**Comment by durack1** [comment]
@matthew-mizielinski an additional time axis is a fairly major change, but will certainly aid the use of CMOR for forecast production generation.

It would be nice to build out the CI testing as this work begins, I have a feeling that unless we have pretty good code coverage some quirks could be introduced, I am sure that @taylor13 will have some insights

**Comment by taylor13** [comment]
@martinjuckes (cc @matthew-mizielinski @piotr-florek-mohc ) 
Could you please check with the Copernicus folks and ask them to clarify what their requirements are?   Will any *time-mean* forecast fields be archived, or only synoptic fields?  If they plan to archive time-mean forecast fields (or accumulated "sum" fields), should there be bounds on the *leadtime* auxiliary coordiante associated with these time means, or can the bounds be omitted (nb.: the bounds *will be* saved as part of the actual "time" coordinate.).  Also, should the "leadtime" *coordinate* record the beginning, middle, or end of each time averaging period?  [Note for CMIP, all time-mean fields have time-coordinate values that record the *middle* of a time averaging period.]

**Comment by taylor13** [comment]
Also, would be nice if PrePARE (the CMOR checker) would be able to check that these new forecast requirements had been met.

**Comment by piotr-florek-mohc** [comment]
Hi Karl,
thank you for your thoughtful comments. I agree that the "quick and dirty" approach implemented in #623 might be a bit too much on the "dirty" side, and it would be much better to align this modification with the standard CMOR api, using MIP tables to enable new time coordinates instead of relying on a call of my bespoke function. My C is now slightly better than it used to be, and I have learned a bit more about CMOR's structure; so I'll take what I had done as a starting point and will try to edge it towards more elegant solution.

**Comment by taylor13** [comment]
I should say that I appreciate your strategy of implementing changes in the way that would likely minimize the chance of causing some subtle conflicts with the rest of CMOR.  That was sensible and smart.  So the idea of *not* trying to integrate them with the rest of the structure might still be the best way to go.  But thanks for thinking about some other options.

**Comment by wachsylon** [comment]
Hi all,
I also liked the detailled description of @taylor13 very much. I am running it as a thought experiment for a hypothetical cmip7 and I do not understand how a *flag* can be used for additional dimensions.
Wouldn't we need **two** variable entries in one table, e.g., `Amon` :
```
tas
dimensions : time
..
tasForceast
dimensions: time reftime leadtime
```
?
I fear I make things more complicated but if there could be an approach similar to `alevel` dimension where more than one coordinate is allowed for the dimension of the corresponding variable, we would save additional variable entries. It could look like that:

```
tas
dimensions : tlev
```

and in `coordinate.json` we would have

```
reftime
            "generic_level_name": "tlev"
```

**Comment by piotr-florek-mohc** [comment]
Hi @taylor13
Apologies for late reply, I wanted to make sure that I could make it backward compatible, and while that is the case, it's not the most elegant solution and I'm not entirely happy with the way I implemented it.

One of the complications is that `reftime` was already implemented in `3.2.4` (most of it in  4676b7d82bd3d6c9b63cd560b67bad6a1a440237), and it complicated CMOR's axis handling a bit. I don't quite follow what happens there, so I couldn't make my code work without breaking that bit, so in the end I call the `leadtime` creating function as a special case after everything else is done.

**Comment by mauzey1** [comment]
@piotr-florek-mohc 

Looking over the new features added to CMOR in #634, I've noticed that there is a function in cmor_func_def.h that is not defined anywhere.

https://github.com/PCMDI/cmor/blob/847179fbf3763b47bd73d57ff177edafbf18e34d/include/cmor_func_def.h#L111

Is the function `calculate_leadtime_coord` meant to be `cmor_calculate_leadtime_coord`?

I've also noticed that there is a Python interface for the function but not for Fortran.  Should we have one?

**Comment by mauzey1** [comment]
I'm guessing this issue can be closed since the lead time coordinate has already been added to CMOR via #634.  Please reopen if further work is needed.
