### ISSUE TITLE
cmor_time_varying_grid_coordinate returns error

### ISSUE THREAD

**Issue by goord** [PCMDI/cmor#89]
In the attached fortran code, I seem to succesfully create a grid, but when I request the latitude variable id, cmor complains it cannot find such a coordinate:

```
C Traceback:
! In function: cmor_variable
! called from: cmor_time_varying_grid_coordinate
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: Could not find a matching variable for name: 'latitude'
!
!!!!!!!!!!!!!!!!!!!!!!!!!

```

[cmor_test.zip](https://github.com/PCMDI/cmor/files/434498/cmor_test.zip)

**Comment by dnadeau4** [comment]
I have started to work on it, it seems that Fortran confused tables for some reason.   I hope I can fix it tomorrow.

**Comment by dnadeau4** [comment]
@goord I was able to run your program.  The main problem is that you were calling cmor_write with the `idl` variable, but `cmor` knows about `idl` since you called `cmor_time_varying_grid_coordinate` using `idg`,  `cmor_write` will create everything, you don't need to call it twice. 

The other strange thing is that you do not use `time` as a axis for `cmor_time_varying_grid_coordinate` .  Refer to this [example](https://github.com/PCMDI/cmor/blob/master/Test/test_cmor_grid_time_varying.f90#L115-L144).  This is one of the few examples  that I have not translated to CMIP6 using `cmor_dataset_json`  yet.  
[cmor3_test.zip](https://github.com/PCMDI/cmor/files/438512/cmor3_test.zip)

**Comment by goord** [comment]
Thanks for the quick reply. The code runs without errors if I remove the cmor_write call for the latitudes, but the resulting netcdf file contains only zeros for latitudes. It does contain the time axis properly, it apparently added this because of the time-dependent variable tos.

**Comment by dnadeau4** [comment]
@goord I am not sure if you are using anaconda.  I fixed that zeros latitude bug in branch [cmor-3.1.2](https://github.com/PCMDI/cmor/tree/cmor-3.1.2).  I am trying to create a new release, but people are still changing the data structure of CMIP6_CV file which causes delays.  

Your output file is correct but a little bit overloaded since you have the same lat/lon for every row/column of the grid.   I thought your latitude was changing over time like in calipso sampling where latitude depends on time/location.  

Here is what I would do....

You should try to create 3 different axes as in this [example](https://github.com/PCMDI/cmor/blob/cmor-3.1.2/Test/test_sophie.f90):

   * time ( you already have it)
   * alats will contains 1 vector of latitudes (grid middle point)
   * alons will contains 1 vector of longitudes (grid middle point)
   * bnds_lat  -- latitudes boundaries (grid edges)
   * bnds_lon -- longitude boundaries (grid edges)

```fortran
  ilat = cmor_axis(  &
       table='Tables/CMIP6_Omon.json',    &
       table_entry='latitude',       &
       units='degrees_north',        &
       length=n_lats,                   &
       coord_vals=alats,             &
       cell_bounds=bnds_lat)

  ilon = cmor_axis(  &
       table='Tables/CMIP6_Amon.json',    &
       table_entry='longitude',      &
       length=n_lons,                   &
       units='degrees_east',         &
       coord_vals=alons,             &
       cell_bounds=bnds_lon)

  !   note that the time axis is defined next, but the time coordinate 
  !   values and bounds will be passed to cmor through function 
  !   cmor_write (later, below).

    idt=cmor_axis(table=trim(table),&
                  table_entry="time",&
                  units="seconds since 2000-01-01",&
                  length=n_steps,&
                  interval=time_step,&
                  coord_vals=tims,&
                  cell_bounds=timbnds)

    idv=cmor_variable(table=trim(table),&
                      table_entry=trim(var_name),&
                      axis_ids=(/ilon, ilat, idt/),&
                      units=var_unit,&
                      positive="",&
                      original_name="kweenie")

        error_flag = cmor_write(                                  &
             var_id        = idv ,                        &
             data          = tos,                              &
             ntimes_passed = 10,                                   &
             time_vals     = n_step,                                &
             time_bnds     = timbnds  )

)```

**Comment by goord** [comment]
@dnadeau4 Thanks for your suggestions, the test program runs and produces the expected output when I link it against cmor-3.1.2. BTW I know the arrays contain a lot of redundant information, but it is a simplification of a more complicated grid which needs the 2d-arrays for the lat and lon arrays.

I shall continue using the cmor-3.1.2 version until a new official release tag is presented.
