### ISSUE TITLE
Issues with the CMIP6 MIP tables

### ISSUE THREAD

**Issue by ehogan** [PCMDI/cmor#91]
I have discovered a few issues with the CMIP6 MIP tables:
- The [p220](https://github.com/PCMDI/cmor/blob/master/TestTables/CMIP6_6hrPlev.json#L894) and [p840](https://github.com/PCMDI/cmor/blob/master/TestTables/CMIP6_6hrPlev.json#L982) axes in the [CMIP6_6hrPlev](https://github.com/PCMDI/cmor/blob/master/TestTables/CMIP6_6hrPlev.json) MIP table should be called `p200` and `p850`, since the dimensions used in this MIP table have the names `p200` and `p850`.
- Some of the variables in the MIP tables have both `valid_min` = `"0"` and `valid_max` = `"0"`, which causes CMOR3 to error, for example​ [siage](https://github.com/PCMDI/cmor/blob/master/TestTables/CMIP6_SImon.json#L2357) in the [CMIP6_SImon](https://github.com/PCMDI/cmor/blob/master/TestTables/CMIP6_SImon.json) MIP table.
- All the `cell_methods` and `cell_measures` appear to be the wrong way around, for example [ps](https://github.com/PCMDI/cmor/blob/master/TestTables/CMIP6_Amon.json#L2208) in the [CMIP6_Amon](https://github.com/PCMDI/cmor/blob/master/TestTables/CMIP6_Amon.json) MIP table.

**Comment by dnadeau4** [comment]
1. `p200` and `p850` do not exist in martin's table: http://clipc-services.ceda.ac.uk/dreq/index/grids.html

1.  if I see that `valid_min == valid_max` I will just ignore them, otherwise cmor will never pass.  

1. @martinjuckes told me about the 3rd issue.  I will fix it pronto.  Thanks for reminding me.

Note: the tables follow Martin's dreq.xml and vocab.xml file found in his repository.  Each time he updates, I have to updates all the CMIP6 tables. 

* http://proj.badc.rl.ac.uk/svn/exarch/CMIP6dreq/tags/latest/dreqPy/docs/
* http://proj.badc.rl.ac.uk/svn/exarch/CMIP6dreq/tags/latest/dreqPy/docs/dreq.xml

**Comment by dnadeau4** [comment]
I am not sure whey I do not have `p200` and `p850` in my tables.  They seems to be in `dreq.xml`.  I will check this for 3.2.0 release.

**Comment by ehogan** [comment]
Related to this, I noticed the `external_variables` attribute is written to the output netCDF files with the correct value `areacella`, even though `areacella` is (currently and incorrectly) the value of the `cell_methods` attribute (rather than the `cell_measures` attribute) in the MIP table. If I edit the MIP table to swap the values for the `cell_methods` and `cell_measures` attributes so that the `cell_measures` attribute contains the correct value, CMOR fails with a `Dataset error, required attribute external_variables was not passed or blanked` error.

**Comment by ehogan** [comment]
@dnadeau4 I've just finished testing CMOR 3.1.3 with the latest version of the MIP tables (01.beta.38) and all these issues have been resolved; thank you very much!
